from typing import Any, Callable
import logging

from rq.job import Job

LOGGER: logging.Logger

def prepare_containment(scheduler_pid: int | None = ...) -> dict[int, int]: ...
def terminate_adopted_writers(
    heartbeat: Callable[[], Any], monitoring_interval: int, protected: dict[int, int]
) -> None: ...
def has_remaining_writers(protected: dict[int, int]) -> bool: ...
def record_cleanup(job: Job, execution_id: str, state: str, **details: Any) -> None: ...
def cleanup_stopped_execution(worker: Any, job: Job) -> None: ...
