from __future__ import annotations


def _prep_multi_ofe_rq(runid: str) -> None: ...


def _prep_slopes_rq(runid: str) -> None: ...


def _run_hillslopes_rq(runid: str) -> None: ...


def _run_flowpaths_rq(runid: str) -> None: ...


def _prep_managements_rq(runid: str) -> None: ...


def _prep_soils_rq(runid: str) -> None: ...


def _prep_climates_rq(runid: str) -> None: ...


def _prep_remaining_rq(runid: str) -> None: ...


def _prep_watershed_rq(runid: str) -> None: ...
