from __future__ import annotations


def _post_run_cleanup_out_rq(runid: str) -> None: ...


def _analyze_return_periods_rq(runid: str) -> None: ...


def _build_hillslope_interchange_rq(runid: str) -> None: ...


def _build_totalwatsed3_rq(runid: str) -> None: ...


def _run_hillslope_watbal_rq(runid: str) -> None: ...


def _post_prep_details_rq(runid: str) -> None: ...


def _post_watershed_interchange_rq(runid: str) -> None: ...


def _post_legacy_arc_export_rq(runid: str) -> None: ...


def _post_gpkg_export_rq(runid: str) -> None: ...


def post_dss_export_rq(runid: str) -> None: ...


def _post_make_loss_grid_rq(runid: str) -> None: ...
