from __future__ import annotations

from dataclasses import dataclass
from contextlib import AbstractContextManager
from enum import StrEnum
from typing import Callable, Iterable, Mapping, Protocol

from wepppy.rq.weppcloudr_backends import KubernetesRenderError, RenderRequest

class ReceiptState(StrEnum):
    CREATING = ...
    CREATE_AMBIGUOUS = ...
    ACTIVE = ...
    TERMINAL_SUCCESS = ...
    TERMINAL_FAILURE = ...
    CLEANED = ...

class JobPhase(StrEnum):
    ABSENT = ...
    PENDING = ...
    RUNNING = ...
    SUCCEEDED = ...
    FAILED = ...
    DELETING = ...
    SUSPENDED = ...

@dataclass(frozen=True)
class ControlPlaneConfig:
    namespace: str
    renderer_image_digest: str
    renderer_image_repository: str
    run_pvc: str
    geodata_pvc: str
    service_account: str
    max_active_renders: int
    active_deadline_seconds: int = ...
    pending_timeout_seconds: int = ...
    completed_ttl_seconds: int = ...
    create_reconcile_grace_seconds: int = ...
    cancellation_grace_seconds: int = ...
    run_root_mappings: tuple[tuple[str, str], ...] = ...
    cpu_request: str = ...
    cpu_limit: str = ...
    memory_request: str = ...
    memory_limit: str = ...
    def validate(self) -> None: ...

@dataclass(frozen=True)
class ExecutionReceipt:
    rq_job_id: str
    request_digest: str
    state: ReceiptState
    backend: str
    namespace: str
    job_name: str
    job_uid: str | None
    ownership_nonce: str
    spec_digest: str
    renderer_image_digest: str
    deployment_revision: str
    fencing_generation: int
    created_at: float
    create_attempted_at: float | None = ...
    job_created_at: float | None = ...
    started_at: float | None = ...
    ended_at: float | None = ...
    cancellation_requested: bool = ...
    cancellation_requested_at: float | None = ...
    cleanup_state: str | None = ...
    terminal_state: str | None = ...
    error_code: str | None = ...
    reason: str | None = ...
    artifact_path: str | None = ...
    artifact_sha256: str | None = ...
    artifact_size: int | None = ...
    never_created: bool = ...
    stdout_ref: str | None = ...
    stderr_ref: str | None = ...
    def payload(self) -> dict[str, object]: ...

@dataclass(frozen=True)
class JobObservation:
    phase: JobPhase
    uid: str | None = ...
    ownership_nonce: str | None = ...
    request_digest: str | None = ...
    spec_digest: str | None = ...
    renderer_image_digest: str | None = ...
    deployment_revision: str | None = ...
    reason: str | None = ...
    exit_code: int | None = ...
    artifact_path: str | None = ...
    artifact_sha256: str | None = ...
    artifact_size: int | None = ...
    result_rq_job_id: str | None = ...
    result_request_digest: str | None = ...
    result_fencing_generation: int | None = ...
    stdout_ref: str | None = ...
    stderr_ref: str | None = ...

class CreateAmbiguous(RuntimeError): ...
class ReceiptConflict(RuntimeError): ...

class ReceiptStore(Protocol):
    def get(self, rq_job_id: str) -> ExecutionReceipt | None: ...
    def replace(self, expected: ExecutionReceipt, updated: ExecutionReceipt) -> None: ...
    def acquire_permit(self, rq_job_id: str, nonce: str, maximum: int) -> bool: ...
    def release_permit(self, rq_job_id: str, nonce: str) -> None: ...
    def persist_cancellation(self, rq_job_id: str, request_digest: str) -> None: ...
    def cancellation_requested(self, rq_job_id: str, request_digest: str) -> bool: ...
    def prepare_execution_files(self, request: RenderRequest, request_digest: str, fencing_generation: int) -> tuple[str, str]: ...
    def iter_reconcilable(self) -> Iterable[ExecutionReceipt]: ...
    def acknowledge_event(self, receipt: ExecutionReceipt) -> None: ...
    def initialize(self, request: RenderRequest, namespace: str, job_name: str) -> ExecutionReceipt: ...
    def load_request(self, rq_job_id: str, request_digest: str) -> RenderRequest: ...
    def dispatch_lock(self, rq_job_id: str) -> AbstractContextManager[None]: ...
    def cleanup_execution_files(self, receipt: ExecutionReceipt) -> None: ...

class KubernetesGateway(Protocol):
    def get(self, namespace: str, name: str) -> JobObservation: ...
    def create(self, namespace: str, spec: Mapping[str, object]) -> JobObservation: ...
    def delete_foreground(self, namespace: str, name: str, uid: str) -> None: ...
    def patch_completed_ttl(self, namespace: str, name: str, uid: str, _ttl_seconds: int) -> None: ...

class ReceiptEventSink(Protocol):
    def publish(self, receipt: ExecutionReceipt) -> None: ...
    def publish_error(self, receipt: ExecutionReceipt, error: KubernetesRenderError) -> None: ...

def build_job_spec(
    request: RenderRequest,
    config: ControlPlaneConfig,
    *,
    ownership_nonce: str,
    request_digest: str,
    fencing_generation: int,
    request_subpath: str,
) -> tuple[dict[str, object], str]: ...

class RenderControlPlane:
    def __init__(self, store: ReceiptStore, kubernetes: KubernetesGateway, config: ControlPlaneConfig, *, event_sink: ReceiptEventSink, clock: Callable[[], float] = ...) -> None: ...
    def submit(self, request: RenderRequest) -> ExecutionReceipt: ...
    def observe(self, rq_job_id: str, request_digest: str) -> ExecutionReceipt: ...
    def cancel(self, rq_job_id: str, request_digest: str) -> Mapping[str, object]: ...
    def reap(self) -> list[ExecutionReceipt]: ...
