from __future__ import annotations

from typing import Iterable, List

class SoilMultipleOfeSynth:
    stack: List[str]

    def __init__(self, stack: Iterable[str] | None = ...) -> None: ...
    @property
    def description(self) -> str: ...
    @property
    def num_ofes(self) -> int: ...
    @property
    def stack_of_fns(self) -> bool: ...
    def write(self, dst_fn: str, ksflag: int = ...) -> None: ...
