from __future__ import annotations

import logging
import os
import subprocess
from datetime import datetime
from pathlib import Path

LOGGER = logging.getLogger(__name__)

def resolve_asset_version() -> str:
    """Return a stable asset version string for cache busting."""
    env_version = os.getenv("ASSET_VERSION")
    if env_version:
        return env_version.strip()

    repo_root = Path(__file__).resolve().parents[3]
    try:
        git_version = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=repo_root,
            text=True,
        ).strip()
        if git_version:
            return git_version
    except Exception:
        LOGGER.debug("Falling back to timestamp for asset version", exc_info=True)

    return datetime.utcnow().strftime("%Y%m%d%H%M%S")


def resolve_controllers_gl_build_id(path: Path) -> str | None:
    """Return the build id embedded in controllers-gl.js, or None if unavailable.

    Reads the header block generated by `build_controllers_js.py` and extracts
    the `Build date:` line. Callers should treat None as "unknown" and avoid
    triggering stale-client UX based solely on a missing value.
    """
    build_id: str | None = None
    try:
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            for _ in range(80):
                line = handle.readline()
                if not line:
                    break
                if "Build date:" not in line:
                    continue
                build_id = line.split("Build date:", 1)[-1].strip()
                if build_id:
                    break
                build_id = None
                break
    except OSError:
        build_id = None

    return build_id
