#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-checkout' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
git lfs post-checkout "$@"

ROOT_DIR=$(git rev-parse --show-toplevel)
COMMIT_HASH=$(git rev-parse HEAD)
echo "$COMMIT_HASH" > "$ROOT_DIR/wepppy/commit_hash"
