from __future__ import annotations

from flask import Blueprint, Response
from typing import Optional

disturbed_bp: Blueprint

def modify_disturbed(runid: str, config: str) -> Response: ...

def reset_disturbed(runid: str, config: str) -> Response: ...

def load_extended_land_soil_lookup(runid: str, config: str) -> Response: ...

def has_sbs(runid: str, config: str) -> Response: ...

def task_modify_disturbed(runid: str, config: str) -> Response: ...

def query_baer_wgs_bounds(runid: str, config: str) -> Response: ...

def query_baer_class_map(runid: str, config: str) -> Response: ...

def task_baer_class_map(runid: str, config: str) -> Response: ...

def task_baer_modify_color_map(runid: str, config: str) -> Response: ...

def resources_baer_sbs(runid: str, config: str) -> Response: ...

def set_firedate(runid: str, config: str) -> Response: ...

def task_upload_sbs(runid: str, config: str) -> Response: ...

def task_upload_cover_transform(runid: str, config: str) -> Response: ...

def task_remove_sbs(runid: str, config: str) -> Response: ...

def task_build_uniform_sbs(runid: str, config: str, value: Optional[str] = ...) -> Response: ...
