[general]
dem_db = "ned1/2022"

[unitizer]
is_english=false

[baer]
legacy_mode=false

[watershed]
delineation_backend = "topaz"
csa=100
pkcsa = "auto"
clip_hillslope_length=300
clip_hillslopes=true
bieger2015_widths=true
walk_flowpaths=true
mofe_target_length=60
mofe_buffer=false
mofe_buffer_length=30
mofe_max_ofes=19
abstraction_backend = "peridot"

[nodb]
default_wepp_type = "granitic"

[landuse]
nlcd_db = "nlcd/2019"
fractionals=[]
mofe_buffer_selection=42

[soils]
ssurgo_db = "ssurgo/2023"
wepp_chn_type = "default"
ksflag=false

[climate]
cligen_db = "2015_stations.db"
daymet_observed  = "daymet/v4"

[disturbed]
sol_ver=7778

[revegetation]
sol_ver=9003

[wepp]
wepp_ui=true
pmet=true
frost=false
tcr=false
baseflow=true
snow=false
channel_erodibility=1E-6
channel_critical_shear=19.0
channel_2006_avke=10.0
channel_manning_roughness_coefficient_bare=0.03
channel_manning_roughness_coefficient_veg=0.04
multi_ofe=false
pmet_kcb=0.95
pmet_rawp=0.8
prep_details_on_run_completion=false
arc_export_on_run_completion=true
legacy_arc_export_on_run_completion=false
dss_export_on_run_completion=false


[tcr_opts]
taumin=35.0
taumax=70.0
kch=0.02
nch=1.0

[ash]
run_wind_transport=false
field_black_ash_bulkdensity=0.31
field_white_ash_bulkdensity=0.14
black_ash_bulkdensity=0.31
white_ash_bulkdensity=0.14

