"""Reusable helper contracts for TerrainProcessor pre-implementation phases.

These helpers are intentionally orchestration-light so future TerrainProcessor
runtime code can compose them without inheriting `WhiteboxToolsTopazEmulator`.
"""

from __future__ import annotations

import csv
import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Sequence

import numpy as np

from wepppy.topo.watershed_abstraction.support import json_to_wgs, polygonize_netful

_FLOW_STACK_REQUIRED_METHODS: tuple[str, ...] = (
    "_create_relief",
    "_create_flow_vector",
    "_create_flow_accumulation",
    "_extract_streams",
    "_identify_stream_junctions",
)

_FLOW_STACK_REQUIRED_PATHS: tuple[str, ...] = (
    "relief",
    "flovec",
    "floaccum",
    "netful",
    "netful_json",
    "chnjnt",
)


def _validate_flow_stack_emulator_contract(emulator: Any) -> None:
    missing_members: list[str] = []
    for method_name in _FLOW_STACK_REQUIRED_METHODS:
        method = getattr(emulator, method_name, None)
        if not callable(method):
            missing_members.append(method_name)
    for attr_name in _FLOW_STACK_REQUIRED_PATHS:
        if not hasattr(emulator, attr_name):
            missing_members.append(attr_name)

    if missing_members:
        missing = ", ".join(sorted(set(missing_members)))
        raise TypeError(
            "emulator is missing required flow-stack contract members: "
            f"{missing}"
        )


@dataclass(frozen=True)
class FlowStackArtifacts:
    """Typed paths emitted by the flow-stack facade helper."""

    relief_path: str
    flow_vector_path: str
    flow_accumulation_path: str
    stream_raster_path: str
    stream_geojson_path: str
    stream_junctions_path: str


def derive_flow_stack(
    emulator: Any,
    *,
    csa: float,
    mcl: float,
    fill_or_breach: str = "fill",
    blc_dist: int | None = None,
    blc_max_cost: float | None = None,
    blc_fill: bool = True,
    polygonize_streams: Callable[[str, str], None] = polygonize_netful,
    reproject_streams_geojson: Callable[[str], None] = json_to_wgs,
) -> FlowStackArtifacts:
    """Execute the flow-stack sequence and return a typed artifact bundle.

    Args:
        emulator: WhiteboxToolsTopazEmulator-like object exposing required
            primitive methods and path properties.
        csa: Channel source area threshold in hectares.
        mcl: Minimum channel length in meters.
        fill_or_breach: Conditioning strategy used for relief generation.
        blc_dist: Optional least-cost breach distance value.
        blc_max_cost: Optional least-cost cumulative cost limit.
        blc_fill: Whether least-cost breach should fill unresolved pits.
        polygonize_streams: Hook for stream raster polygonization.
        reproject_streams_geojson: Hook that creates a WGS84 stream GeoJSON.

    Returns:
        A :class:`FlowStackArtifacts` containing generated artifact paths.
    """
    if csa <= 0:
        raise ValueError("csa must be greater than zero")
    if mcl <= 0:
        raise ValueError("mcl must be greater than zero")
    if fill_or_breach not in {"fill", "breach", "breach_least_cost"}:
        raise ValueError("fill_or_breach must be 'fill', 'breach', or 'breach_least_cost'")
    if blc_max_cost is not None and blc_max_cost <= 0:
        raise ValueError("blc_max_cost must be greater than zero when provided")
    if not isinstance(blc_fill, bool):
        raise ValueError("blc_fill must be a boolean")
    _validate_flow_stack_emulator_contract(emulator)

    emulator.csa = float(csa)
    emulator.mcl = float(mcl)

    emulator._create_relief(
        fill_or_breach=fill_or_breach,
        blc_dist=blc_dist,
        blc_max_cost=blc_max_cost,
        blc_fill=blc_fill,
    )
    emulator._create_flow_vector()
    emulator._create_flow_accumulation()
    emulator._extract_streams()
    emulator._identify_stream_junctions()

    polygonize_streams(emulator.netful, emulator.netful_json)
    reproject_streams_geojson(emulator.netful_json)

    return FlowStackArtifacts(
        relief_path=emulator.relief,
        flow_vector_path=emulator.flovec,
        flow_accumulation_path=emulator.floaccum,
        stream_raster_path=emulator.netful,
        stream_geojson_path=emulator.netful_json,
        stream_junctions_path=emulator.chnjnt,
    )


@dataclass(frozen=True)
class BoundedBreachArtifacts:
    """Typed artifact paths generated by bounded-breach helper orchestration."""

    masked_dem_path: str
    breached_interior_path: str
    composite_dem_path: str


def resolve_bounded_breach_collar_pixels(
    *,
    cellsize_m: float,
    bounded_breach_collar_m: float | None,
) -> int:
    """Resolve the collar width in pixels for bounded-breach masking."""
    if cellsize_m <= 0:
        raise ValueError("cellsize_m must be greater than zero")

    collar_m = bounded_breach_collar_m
    if collar_m is None:
        collar_m = 10.0 * cellsize_m

    if collar_m < 0:
        raise ValueError("bounded_breach_collar_m cannot be negative")
    if collar_m == 0:
        return 0

    collar_px = int(round(collar_m / cellsize_m))
    return max(1, collar_px)


def _coerce_bool_mask(mask_array: np.ndarray, nodata_value: Any) -> np.ndarray:
    if nodata_value is None:
        valid = np.ones(mask_array.shape, dtype=bool)
    elif isinstance(nodata_value, float) and np.isnan(nodata_value):
        valid = ~np.isnan(mask_array)
    else:
        valid = mask_array != nodata_value
    return valid & (mask_array != 0)


def dilate_boolean_mask(mask: np.ndarray, pixels: int) -> np.ndarray:
    """Dilate a boolean mask by N pixels using an 8-neighbor kernel."""
    if pixels < 0:
        raise ValueError("pixels cannot be negative")

    dilated = mask.astype(bool)
    for _ in range(pixels):
        padded = np.pad(dilated, 1, mode="constant", constant_values=False)
        dilated = (
            padded[:-2, :-2]
            | padded[:-2, 1:-1]
            | padded[:-2, 2:]
            | padded[1:-1, :-2]
            | padded[1:-1, 1:-1]
            | padded[1:-1, 2:]
            | padded[2:, :-2]
            | padded[2:, 1:-1]
            | padded[2:, 2:]
        )
    return dilated


def _resolve_output_nodata(input_nodata: Any, dtype: np.dtype) -> Any:
    if input_nodata is not None:
        return input_nodata
    if np.issubdtype(dtype, np.floating):
        return np.nan
    if np.issubdtype(dtype, np.integer):
        return np.iinfo(dtype).min
    raise ValueError(f"Unsupported raster dtype for nodata fallback: {dtype}")


def create_masked_dem(
    *,
    prepared_dem_path: str,
    boundary_mask_path: str,
    output_masked_dem_path: str,
    collar_pixels: int,
) -> str:
    """Create the interior-mask DEM used by bounded-breach execution."""
    if collar_pixels < 0:
        raise ValueError("collar_pixels cannot be negative")

    import rasterio

    with rasterio.open(prepared_dem_path) as dem_ds, rasterio.open(boundary_mask_path) as boundary_ds:
        if dem_ds.width != boundary_ds.width or dem_ds.height != boundary_ds.height:
            raise ValueError("prepared_dem and boundary_mask dimensions must match")

        prepared_dem = dem_ds.read(1)
        boundary_mask = boundary_ds.read(1)
        boundary = _coerce_bool_mask(boundary_mask, boundary_ds.nodata)
        collar_mask = dilate_boolean_mask(boundary, collar_pixels)

        nodata_value = _resolve_output_nodata(dem_ds.nodata, prepared_dem.dtype)
        masked_dem = prepared_dem.copy()
        masked_dem[~collar_mask] = nodata_value

        output_profile = dem_ds.profile.copy()
        output_profile["nodata"] = nodata_value

    output_path = Path(output_masked_dem_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with rasterio.open(output_path, "w", **output_profile) as out_ds:
        out_ds.write(masked_dem, 1)

    return str(output_path)


def create_bounded_breach_composite(
    *,
    filled_dem_path: str,
    breached_interior_path: str,
    boundary_mask_path: str,
    output_composite_dem_path: str,
) -> str:
    """Composite bounded-breach output: breached interior + filled exterior."""
    import rasterio

    with rasterio.open(filled_dem_path) as filled_ds, rasterio.open(
        breached_interior_path
    ) as breached_ds, rasterio.open(boundary_mask_path) as boundary_ds:
        same_shape = (
            filled_ds.width == breached_ds.width == boundary_ds.width
            and filled_ds.height == breached_ds.height == boundary_ds.height
        )
        if not same_shape:
            raise ValueError("filled, breached, and boundary rasters must have matching dimensions")

        filled = filled_ds.read(1)
        breached = breached_ds.read(1)
        boundary_mask = boundary_ds.read(1)

        boundary = _coerce_bool_mask(boundary_mask, boundary_ds.nodata)
        composite = np.where(boundary, breached, filled).astype(filled.dtype, copy=False)

        output_profile = filled_ds.profile.copy()

    output_path = Path(output_composite_dem_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with rasterio.open(output_path, "w", **output_profile) as out_ds:
        out_ds.write(composite, 1)

    return str(output_path)


def run_bounded_breach_workflow(
    *,
    prepared_dem_path: str,
    boundary_mask_path: str,
    filled_dem_path: str,
    output_masked_dem_path: str,
    output_breached_interior_path: str,
    output_composite_dem_path: str,
    collar_pixels: int,
    breach_runner: Callable[[str, str], None],
) -> BoundedBreachArtifacts:
    """Run bounded-breach helper workflow with an injected breach adapter.

    This helper assumes the fill-first pass and boundary-mask derivation were
    completed upstream. It then prepares the interior mask, runs breach on the
    masked DEM, and composites interior/exterior DEM values.
    """
    if not callable(breach_runner):
        raise TypeError("breach_runner must be callable")

    masked_dem_path = create_masked_dem(
        prepared_dem_path=prepared_dem_path,
        boundary_mask_path=boundary_mask_path,
        output_masked_dem_path=output_masked_dem_path,
        collar_pixels=collar_pixels,
    )

    breach_runner(masked_dem_path, output_breached_interior_path)
    if not os.path.exists(output_breached_interior_path):
        raise FileNotFoundError(
            f"breach_runner did not create interior breach output: {output_breached_interior_path}"
        )

    composite_dem_path = create_bounded_breach_composite(
        filled_dem_path=filled_dem_path,
        breached_interior_path=output_breached_interior_path,
        boundary_mask_path=boundary_mask_path,
        output_composite_dem_path=output_composite_dem_path,
    )

    return BoundedBreachArtifacts(
        masked_dem_path=masked_dem_path,
        breached_interior_path=output_breached_interior_path,
        composite_dem_path=composite_dem_path,
    )


class TerrainProcessorHelperError(Exception):
    """Base class for helper-contract failures with machine-readable codes."""

    def __init__(self, message: str, *, code: str) -> None:
        super().__init__(message)
        self.message = message
        self.code = code


class GeometryInputError(TerrainProcessorHelperError):
    def __init__(self, message: str) -> None:
        super().__init__(message, code="geometry_input_error")


class CulvertSnapError(TerrainProcessorHelperError):
    def __init__(self, message: str) -> None:
        super().__init__(message, code="culvert_snap_error")


class BurnStreamsAtRoadsValidationError(TerrainProcessorHelperError):
    def __init__(self, message: str) -> None:
        super().__init__(message, code="burn_streams_at_roads_validation_error")


def _load_feature_collection(source: str | Path | Mapping[str, Any]) -> dict[str, Any]:
    if isinstance(source, (str, Path)):
        try:
            with open(source) as fp:
                payload = json.load(fp)
        except OSError as exc:
            raise GeometryInputError(f"Unable to read GeoJSON source: {source}") from exc
        except json.JSONDecodeError as exc:
            raise GeometryInputError(f"GeoJSON source is not valid JSON: {source}") from exc
    else:
        try:
            payload = dict(source)
        except TypeError as exc:
            raise GeometryInputError("GeoJSON payload must be a mapping or file path") from exc

    if payload.get("type") != "FeatureCollection":
        raise GeometryInputError("GeoJSON payload must be a FeatureCollection")

    features = payload.get("features")
    if not isinstance(features, list):
        raise GeometryInputError("GeoJSON FeatureCollection must include a features list")

    return payload


def _as_shapely_geometry(geometry_payload: Mapping[str, Any]) -> Any:
    from shapely import errors as shapely_errors
    from shapely.geometry import shape

    geos_exception_type = getattr(shapely_errors, "GEOSException", ValueError)
    try:
        return shape(geometry_payload)
    except (TypeError, ValueError, KeyError, geos_exception_type) as exc:
        raise GeometryInputError(f"Invalid geometry payload: {geometry_payload}") from exc


def _flatten_intersection_points(geometry: Any) -> list[Any]:
    if geometry.is_empty:
        return []

    geom_type = geometry.geom_type
    if geom_type == "Point":
        return [geometry]
    if geom_type == "MultiPoint":
        return list(geometry.geoms)
    if geom_type in {"LineString", "LinearRing", "Polygon", "MultiLineString", "MultiPolygon"}:
        return [geometry.representative_point()]
    if geom_type == "GeometryCollection":
        flattened: list[Any] = []
        for child in geometry.geoms:
            flattened.extend(_flatten_intersection_points(child))
        return flattened

    return [geometry.representative_point()]


def extract_road_stream_intersections(
    roads_geojson: str | Path | Mapping[str, Any],
    streams_geojson: str | Path | Mapping[str, Any],
    *,
    round_precision: int = 6,
) -> dict[str, Any]:
    """Extract deduplicated point intersections between roads and streams."""
    from shapely import errors as shapely_errors

    geos_exception_type = getattr(shapely_errors, "GEOSException", ValueError)
    roads_fc = _load_feature_collection(roads_geojson)
    streams_fc = _load_feature_collection(streams_geojson)

    roads = []
    for feature in roads_fc["features"]:
        geometry_payload = feature.get("geometry")
        if geometry_payload is None:
            continue
        roads.append(_as_shapely_geometry(geometry_payload))

    streams = []
    for feature in streams_fc["features"]:
        geometry_payload = feature.get("geometry")
        if geometry_payload is None:
            continue
        streams.append(_as_shapely_geometry(geometry_payload))

    intersections: list[tuple[float, float]] = []
    seen: set[tuple[float, float]] = set()

    for road_geom in roads:
        for stream_geom in streams:
            try:
                intersection = road_geom.intersection(stream_geom)
            except geos_exception_type as exc:
                raise GeometryInputError(
                    "Unable to compute road-stream intersection geometry"
                ) from exc
            for point in _flatten_intersection_points(intersection):
                coord = (round(float(point.x), round_precision), round(float(point.y), round_precision))
                if coord in seen:
                    continue
                seen.add(coord)
                intersections.append(coord)

    features = [
        {
            "type": "Feature",
            "properties": {"id": idx},
            "geometry": {"type": "Point", "coordinates": [x, y]},
        }
        for idx, (x, y) in enumerate(intersections)
    ]

    return {"type": "FeatureCollection", "features": features}


def load_culvert_points(
    culvert_points_geojson: str | Path | Mapping[str, Any]
) -> dict[str, Any]:
    """Load uploaded culvert points and normalize MultiPoint features to points."""
    payload = _load_feature_collection(culvert_points_geojson)

    normalized_features: list[dict[str, Any]] = []
    next_id = 0
    for feature in payload["features"]:
        geometry_payload = feature.get("geometry")
        if geometry_payload is None:
            continue

        geom = _as_shapely_geometry(geometry_payload)
        props = dict(feature.get("properties") or {})

        if geom.geom_type == "Point":
            normalized_features.append(
                {
                    "type": "Feature",
                    "properties": {**props, "id": next_id},
                    "geometry": {"type": "Point", "coordinates": [float(geom.x), float(geom.y)]},
                }
            )
            next_id += 1
            continue

        if geom.geom_type == "MultiPoint":
            for sub_geom in geom.geoms:
                normalized_features.append(
                    {
                        "type": "Feature",
                        "properties": {**props, "id": next_id},
                        "geometry": {
                            "type": "Point",
                            "coordinates": [float(sub_geom.x), float(sub_geom.y)],
                        },
                    }
                )
                next_id += 1
            continue

        raise GeometryInputError(
            f"Culvert features must be Point/MultiPoint geometries; got {geom.geom_type}"
        )

    return {"type": "FeatureCollection", "features": normalized_features}


def snap_uploaded_culvert_points_to_crossings(
    *,
    uploaded_culvert_points: str | Path | Mapping[str, Any],
    crossing_points: str | Path | Mapping[str, Any],
    max_snap_distance_m: float,
    round_precision: int = 6,
) -> dict[str, Any]:
    """Snap uploaded culvert points to nearest derived road-stream crossings."""
    if max_snap_distance_m <= 0:
        raise CulvertSnapError("max_snap_distance_m must be greater than zero")

    uploads_fc = load_culvert_points(uploaded_culvert_points)
    crossings_fc = load_culvert_points(crossing_points)

    if not crossings_fc["features"]:
        raise CulvertSnapError("crossing_points contained no usable point features")

    from shapely.geometry import Point

    crossing_geoms = []
    for feature in crossings_fc["features"]:
        x, y = feature["geometry"]["coordinates"]
        crossing_geoms.append((Point(float(x), float(y)), feature))

    snapped_features: list[dict[str, Any]] = []
    seen_coords: set[tuple[float, float]] = set()

    for upload_feature in uploads_fc["features"]:
        ux, uy = upload_feature["geometry"]["coordinates"]
        upload_point = Point(float(ux), float(uy))

        best_feature = None
        best_distance = None
        for crossing_geom, crossing_feature in crossing_geoms:
            distance = upload_point.distance(crossing_geom)
            if best_distance is None or distance < best_distance:
                best_distance = distance
                best_feature = crossing_feature

        if best_feature is None or best_distance is None:
            continue
        if best_distance > max_snap_distance_m:
            continue

        cx, cy = best_feature["geometry"]["coordinates"]
        dedupe_key = (round(float(cx), round_precision), round(float(cy), round_precision))
        if dedupe_key in seen_coords:
            continue
        seen_coords.add(dedupe_key)

        snapped_features.append(
            {
                "type": "Feature",
                "properties": {
                    "id": len(snapped_features),
                    "source_culvert_id": upload_feature["properties"].get("id"),
                    "snap_distance_m": float(best_distance),
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [float(cx), float(cy)],
                },
            }
        )

    if not snapped_features:
        raise CulvertSnapError(
            "No uploaded culvert points were within max_snap_distance_m of any crossing"
        )

    return {"type": "FeatureCollection", "features": snapped_features}


def burn_streams_at_roads_adapter(
    *,
    wbt: Any,
    dem_path: str,
    streams_path: str,
    roads_path: str,
    output_path: str,
    road_width_m: float,
) -> str:
    """Validate and execute `BurnStreamsAtRoads` through a WBT runner."""
    if road_width_m <= 0:
        raise BurnStreamsAtRoadsValidationError("road_width_m must be greater than zero")

    for required_path, label in (
        (dem_path, "dem_path"),
        (streams_path, "streams_path"),
        (roads_path, "roads_path"),
    ):
        if not required_path:
            raise BurnStreamsAtRoadsValidationError(f"{label} must be provided")
        if not os.path.exists(required_path):
            raise BurnStreamsAtRoadsValidationError(f"{label} does not exist: {required_path}")

    if not hasattr(wbt, "burn_streams_at_roads"):
        raise BurnStreamsAtRoadsValidationError("wbt runner does not expose burn_streams_at_roads")

    output_parent = Path(output_path).parent
    output_parent.mkdir(parents=True, exist_ok=True)

    wbt.burn_streams_at_roads(
        dem=dem_path,
        streams=streams_path,
        roads=roads_path,
        output=output_path,
        width=float(road_width_m),
    )

    if not os.path.exists(output_path):
        raise BurnStreamsAtRoadsValidationError(
            f"burn_streams_at_roads did not create expected output: {output_path}"
        )

    return output_path


@dataclass(frozen=True)
class BasinSummary:
    """Typed basin record parsed from UnnestBasins hierarchy output."""

    basin_id: int
    parent_basin_id: int | None
    outlet_x: float
    outlet_y: float
    area: float | None = None
    stream_order: int | None = None


def snap_outlets_to_streams(
    outlets: Sequence[tuple[float, float]],
    *,
    snapper: Callable[[float, float], tuple[float, float]],
    dedupe_round_precision: int = 6,
) -> list[tuple[float, float]]:
    """Snap each outlet to streams via injected snapping callable."""
    snapped: list[tuple[float, float]] = []
    seen: set[tuple[float, float]] = set()

    for outlet in outlets:
        if len(outlet) != 2:
            raise ValueError(f"outlet must contain (x, y); got {outlet}")

        snapped_x, snapped_y = snapper(float(outlet[0]), float(outlet[1]))
        dedupe_key = (
            round(float(snapped_x), dedupe_round_precision),
            round(float(snapped_y), dedupe_round_precision),
        )
        if dedupe_key in seen:
            continue
        seen.add(dedupe_key)
        snapped.append((float(snapped_x), float(snapped_y)))

    return snapped


def build_outlet_feature_collection(
    outlets: Sequence[tuple[float, float]],
) -> dict[str, Any]:
    """Convert snapped outlet coordinates to a GeoJSON FeatureCollection."""
    features = [
        {
            "type": "Feature",
            "properties": {"id": idx},
            "geometry": {"type": "Point", "coordinates": [float(x), float(y)]},
        }
        for idx, (x, y) in enumerate(outlets)
    ]
    return {"type": "FeatureCollection", "features": features}


_REQUIRED_HIERARCHY_COLUMN_ALIASES = {
    "basin_id": ("basin_id", "basin", "id", "value", "fid", "outlet_id"),
    "outlet_x": (
        "outlet_x",
        "outlet_easting",
        "x",
        "easting",
        "column",
        "col",
        "outlet_column",
        "outlet_col",
    ),
    "outlet_y": (
        "outlet_y",
        "outlet_northing",
        "y",
        "northing",
        "row",
        "outlet_row",
    ),
}

_OPTIONAL_HIERARCHY_COLUMN_ALIASES = {
    "parent_basin_id": (
        "parent_basin_id",
        "parent_id",
        "parent",
        "pid",
        "parentid",
        "parent_outlet_id",
    ),
    "area": ("area", "area_m2", "basin_area", "watershed_area"),
    "stream_order": ("stream_order", "order", "strahler", "outlet_stream_order"),
}


def _lookup_hierarchy_column(
    available_columns: Mapping[str, str],
    aliases: Sequence[str],
) -> str | None:
    for alias in aliases:
        match = available_columns.get(alias)
        if match is not None:
            return match
    return None


def _parse_required_int(raw_value: str, *, field_name: str, row_num: int) -> int:
    value = str(raw_value).strip()
    if not value:
        raise ValueError(f"Row {row_num}: {field_name} cannot be empty")
    return int(value)


def _parse_optional_parent_id(raw_value: str | None, *, row_num: int) -> int | None:
    if raw_value is None:
        return None
    value = str(raw_value).strip()
    if value == "":
        return None
    parsed = int(value)
    if parsed in {0, -1}:
        return None
    if parsed < -1:
        raise ValueError(f"Row {row_num}: parent_basin_id cannot be less than -1")
    return parsed


def _parse_required_float(raw_value: str, *, field_name: str, row_num: int) -> float:
    value = str(raw_value).strip()
    if not value:
        raise ValueError(f"Row {row_num}: {field_name} cannot be empty")
    return float(value)


def _parse_optional_float(raw_value: str | None) -> float | None:
    if raw_value is None:
        return None
    value = str(raw_value).strip()
    if value == "":
        return None
    return float(value)


def _parse_optional_nonnegative_int(
    raw_value: str | None,
    *,
    field_name: str,
    row_num: int,
) -> int | None:
    if raw_value is None:
        return None
    value = str(raw_value).strip()
    if value == "":
        return None
    parsed = int(value)
    if parsed < 0:
        raise ValueError(f"Row {row_num}: {field_name} cannot be negative")
    return parsed


def parse_unnest_basins_hierarchy_csv(hierarchy_csv_path: str | Path) -> list[BasinSummary]:
    """Parse and validate hierarchy CSV output from `wbt.unnest_basins`."""
    path = Path(hierarchy_csv_path)
    if not path.exists():
        raise FileNotFoundError(f"Hierarchy CSV does not exist: {path}")

    with path.open(newline="") as fp:
        reader = csv.DictReader(fp)
        fieldnames = reader.fieldnames
        if not fieldnames:
            raise ValueError("Hierarchy CSV is missing a header row")

        normalized = {name.strip().lower(): name for name in fieldnames}

        required_columns: dict[str, str] = {}
        for field_name, aliases in _REQUIRED_HIERARCHY_COLUMN_ALIASES.items():
            match = _lookup_hierarchy_column(normalized, aliases)
            if match is None:
                raise ValueError(
                    f"Hierarchy CSV missing required column '{field_name}'. "
                    f"Accepted aliases: {aliases}"
                )
            required_columns[field_name] = match

        optional_columns: dict[str, str] = {}
        for field_name, aliases in _OPTIONAL_HIERARCHY_COLUMN_ALIASES.items():
            match = _lookup_hierarchy_column(normalized, aliases)
            if match is not None:
                optional_columns[field_name] = match

        rows = list(reader)

    basins: list[BasinSummary] = []
    seen_basin_ids: set[int] = set()
    for row_index, row in enumerate(rows, start=2):
        basin_id = _parse_required_int(
            row[required_columns["basin_id"]],
            field_name="basin_id",
            row_num=row_index,
        )
        if basin_id in seen_basin_ids:
            raise ValueError(f"Row {row_index}: duplicate basin_id {basin_id}")
        seen_basin_ids.add(basin_id)

        parent_basin_id = _parse_optional_parent_id(
            row.get(optional_columns.get("parent_basin_id", ""))
            if "parent_basin_id" in optional_columns
            else None,
            row_num=row_index,
        )

        outlet_x = _parse_required_float(
            row[required_columns["outlet_x"]],
            field_name="outlet_x",
            row_num=row_index,
        )
        outlet_y = _parse_required_float(
            row[required_columns["outlet_y"]],
            field_name="outlet_y",
            row_num=row_index,
        )

        area = _parse_optional_float(row.get(optional_columns.get("area", "")) if "area" in optional_columns else None)
        stream_order = _parse_optional_nonnegative_int(
            row.get(optional_columns.get("stream_order", ""))
            if "stream_order" in optional_columns
            else None,
            field_name="stream_order",
            row_num=row_index,
        )

        basins.append(
            BasinSummary(
                basin_id=basin_id,
                parent_basin_id=parent_basin_id,
                outlet_x=outlet_x,
                outlet_y=outlet_y,
                area=area,
                stream_order=stream_order,
            )
        )

    valid_ids = {record.basin_id for record in basins}
    for record in basins:
        parent_id = record.parent_basin_id
        if parent_id is None:
            continue
        if parent_id not in valid_ids:
            raise ValueError(
                f"Basin {record.basin_id} references unknown parent basin {parent_id}"
            )

    return basins


PHASE_SEQUENCE: tuple[str, ...] = (
    "phase1_flow_stack",
    "phase2_bounded_breach",
    "phase3_culvert_enforcement",
    "phase4_multi_outlet",
    "phase5_provenance",
)

DEFAULT_PHASE_INVALIDATION_RULES: dict[str, tuple[str, ...]] = {
    "smooth": PHASE_SEQUENCE,
    "smooth_algorithm": PHASE_SEQUENCE,
    "roads_source": PHASE_SEQUENCE,
    "roads_path": PHASE_SEQUENCE,
    "road_fill_strategy": PHASE_SEQUENCE,
    "conditioning": PHASE_SEQUENCE,
    "blc_dist_m": PHASE_SEQUENCE,
    "blc_max_cost": PHASE_SEQUENCE,
    "bounded_breach_collar_m": PHASE_SEQUENCE[1:],
    "enforce_culverts": PHASE_SEQUENCE[2:],
    "culvert_source": PHASE_SEQUENCE[2:],
    "culvert_path": PHASE_SEQUENCE[2:],
    "culvert_method": PHASE_SEQUENCE[2:],
    "culvert_road_width": PHASE_SEQUENCE[2:],
    "csa": PHASE_SEQUENCE,
    "mcl": PHASE_SEQUENCE,
    "outlet_mode": PHASE_SEQUENCE[3:],
    "outlets": PHASE_SEQUENCE[3:],
    "snap_distance": PHASE_SEQUENCE[3:],
}


@dataclass(frozen=True)
class ProvenanceEntry:
    """Record a single helper step and resulting artifact."""

    step: str
    artifact: str
    parameters: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        record: dict[str, Any] = {
            "step": self.step,
            "artifact": self.artifact,
        }
        if self.parameters:
            record["parameters"] = dict(self.parameters)
        if self.metadata:
            record["metadata"] = dict(self.metadata)
        return record


class TerrainArtifactRegistry:
    """Phase-keyed artifact registry for TerrainProcessor helper outputs."""

    def __init__(self) -> None:
        self._artifacts_by_phase: dict[str, dict[str, str]] = {}

    def register(self, *, phase: str, artifact_name: str, artifact_path: str) -> None:
        if not phase:
            raise ValueError("phase must be non-empty")
        if not artifact_name:
            raise ValueError("artifact_name must be non-empty")
        if not artifact_path:
            raise ValueError("artifact_path must be non-empty")

        phase_bucket = self._artifacts_by_phase.setdefault(phase, {})
        phase_bucket[artifact_name] = artifact_path

    def phase_artifacts(self, phase: str) -> dict[str, str]:
        return dict(self._artifacts_by_phase.get(phase, {}))

    def all_artifacts(self) -> dict[str, dict[str, str]]:
        return {phase: dict(artifacts) for phase, artifacts in self._artifacts_by_phase.items()}


def determine_invalidated_phases(
    *,
    changed_config_keys: Iterable[str],
    invalidation_rules: Mapping[str, Sequence[str]] | None = None,
) -> list[str]:
    """Map config deltas to phase invalidation list ordered by phase sequence."""
    rules = (
        DEFAULT_PHASE_INVALIDATION_RULES
        if invalidation_rules is None
        else invalidation_rules
    )

    invalidated: set[str] = set()
    for key in changed_config_keys:
        phases = rules.get(key)
        if phases is None:
            invalidated.update(PHASE_SEQUENCE)
            continue
        invalidated.update(phases)

    return [phase for phase in PHASE_SEQUENCE if phase in invalidated]


__all__ = [
    "BasinSummary",
    "BoundedBreachArtifacts",
    "BurnStreamsAtRoadsValidationError",
    "CulvertSnapError",
    "DEFAULT_PHASE_INVALIDATION_RULES",
    "FlowStackArtifacts",
    "GeometryInputError",
    "PHASE_SEQUENCE",
    "ProvenanceEntry",
    "TerrainArtifactRegistry",
    "TerrainProcessorHelperError",
    "build_outlet_feature_collection",
    "burn_streams_at_roads_adapter",
    "create_bounded_breach_composite",
    "create_masked_dem",
    "derive_flow_stack",
    "determine_invalidated_phases",
    "dilate_boolean_mask",
    "extract_road_stream_intersections",
    "load_culvert_points",
    "parse_unnest_basins_hierarchy_csv",
    "resolve_bounded_breach_collar_pixels",
    "run_bounded_breach_workflow",
    "snap_outlets_to_streams",
    "snap_uploaded_culvert_points_to_crossings",
]
