from _typeshed import Incomplete
from typing import Any, Dict, List, Optional, Tuple

__all__ = ['Map']

class Map:
    extent: Incomplete
    center: Incomplete
    zoom: Incomplete
    cellsize: Incomplete
    utm: Incomplete
    def __init__(self, extent: List[float], center: List[float], zoom: float, cellsize: float = 30.0) -> None: ...
    @classmethod
    def from_payload(cls, payload: Any, default_cellsize: Optional[float] = None) -> Map: ...
    def to_payload(self) -> Dict[str, Any]: ...
    @staticmethod
    def zoom_for_extent(
        extent: List[float],
        *,
        map_px: Tuple[int, int] = ...,
        tile_px: int = ...,
        min_zoom: float = ...,
        max_zoom: float = ...,
    ) -> float: ...
    @property
    def utm_zone(self) -> int: ...
    @property
    def zone_letter(self) -> str: ...
    @property
    def srid(self) -> int: ...
    @property
    def northern(self) -> bool: ...
    @property
    def ul_x(self) -> float: ...
    @property
    def ul_y(self) -> float: ...
    @property
    def lr_x(self) -> float: ...
    @property
    def lr_y(self) -> float: ...
    @property
    def utm_extent(self) -> Tuple[float, float, float, float]: ...
    @property
    def num_cols(self) -> int: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def shape(self) -> Tuple[int, int]: ...
    @property
    def bounds_str(self) -> str: ...
    def utm_to_px(self, easting: float, northing: float) -> Tuple[int, int]: ...
    def lnglat_to_px(self, lng: float, lat: float) -> Tuple[int, int]: ...
    def px_to_utm(self, x: int, y: int) -> Tuple[float, float]: ...
    def lnglat_to_utm(self, lng: float, lat: float) -> Tuple[float, float]: ...
    def px_to_lnglat(self, x: int, y: int) -> Tuple[float, float]: ...
    def raster_intersection(self, extent: List[float], raster_fn: str, discard: Optional[Any] = None) -> List: ...
