from _typeshed import Incomplete
from typing import Any, ClassVar, Dict, List, Optional, Tuple
from wepppy.nodb.base import NoDbBase
from .map import Map

__all__ = ['Map', 'RonNoDbLockedException', 'Ron', 'RonViewModel']

class RonNoDbLockedException(Exception): ...

class Ron(NoDbBase):
    __name__: ClassVar[str]
    __exclude__: ClassVar[Tuple[str, ...]]
    filename: ClassVar[str]
    def __init__(self, wd: str, cfg_fn: str = '0.cfg', run_group: Optional[str] = None, group_name: Optional[str] = None, initialize_components: bool = True) -> None: ...
    def clean_export_dir(self) -> None: ...
    def init_sbs_map(self, sbs_map: str, baer: Any) -> None: ...
    @property
    def profile_recorder_assembler_enabled(self) -> bool: ...
    @property
    def configname(self) -> str: ...
    @property
    def max_map_dimension_px(self) -> int: ...
    @property
    def enable_landuse_change(self) -> bool: ...
    def remove_mod(self, mod_name: str) -> None: ...
    @property
    def center0(self) -> List[float]: ...
    @property
    def zoom0(self) -> float: ...
    @property
    def cellsize(self) -> float: ...
    @property
    def boundary(self) -> Optional[str]: ...
    @property
    def boundary_color(self) -> str: ...
    @property
    def boundary_name(self) -> str: ...
    @property
    def map(self) -> Optional[Map]: ...
    def set_map(self, extent: List[float], center: List[float], zoom: float) -> None: ...
    def set_map_object(self, map_object: Any) -> None: ...
    @property
    def w3w(self) -> str: ...
    @property
    def location_hash(self) -> str: ...
    @property
    def extent(self) -> Optional[List[float]]: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def scenario(self) -> str: ...
    @scenario.setter
    def scenario(self, value: str) -> None: ...
    @property
    def has_ash_results(self) -> bool: ...
    @property
    def dem_db(self) -> str: ...
    @dem_db.setter
    def dem_db(self, value: str) -> None: ...
    @property
    def dem_map(self) -> Optional[str]: ...
    @dem_map.setter
    def dem_map(self, value: str) -> None: ...
    @property
    def dem_is_vrt(self) -> bool: ...
    @property
    def dem_fn(self) -> str: ...
    @property
    def crop_window(self) -> Tuple[int, int, int, int] | None: ...
    @property
    def crop_reference_geotransform(self) -> Tuple[float, float, float, float, float, float] | None: ...
    @property
    def crop_reference_shape(self) -> Tuple[int, int] | None: ...
    def fetch_dem(self) -> None: ...
    def symlink_dem(
        self,
        dem_fn: str,
        *,
        as_cropped_vrt: bool = False,
        crop_window: Tuple[int, int, int, int] | None = None,
    ) -> None: ...
    @property
    def has_dem(self) -> bool: ...
    def subs_summary(self, abbreviated: bool = False) -> Dict: ...
    def sub_summary(self, topaz_id: Optional[str] = None, wepp_id: Optional[str] = None) -> Dict: ...
    def chns_summary(self, abbreviated: bool = False) -> List[Dict]: ...
    def chn_summary(self, topaz_id: Optional[str] = None, wepp_id: Optional[str] = None) -> Dict: ...

class RonViewModel:
    runid: Incomplete
    name: Incomplete
    scenario: Incomplete
    config_stem: Incomplete
    readonly: Incomplete
    public: Incomplete
    pup_relpath: Incomplete
    def __init__(self, ron: Ron) -> None: ...
    @classmethod
    def getInstanceFromRunID(cls, runid: str) -> RonViewModel: ...
