from pathlib import Path
from typing import Any, FrozenSet

REQUIRED_WEPPPYO3_INTERCHANGE_API: FrozenSet[str]

class WeppInterchangeNativeError(RuntimeError): ...
class WeppInterchangeUnavailableError(WeppInterchangeNativeError): ...
class WeppInterchangeExecutionError(WeppInterchangeNativeError): ...

def require_wepppyo3_interchange(operation: str, *required_symbols: str) -> object: ...
def call_wepppyo3_interchange(operation: str, symbol: str, /, *args: Any, **kwargs: Any) -> Any: ...
def version_args() -> tuple[int, int]: ...
def resolve_cli_calendar_path(
    wepp_output_dir: Path,
    *,
    cli_hint: str | None = ...,
    log: Any | None = ...,
) -> Path | None: ...
