from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, MutableMapping, Optional

LOGGER: logging.Logger
MANIFEST_FILENAME: str

@dataclass(frozen=True, slots=True)
class Version:
    major: int
    minor: int
    def __post_init__(self) -> None: ...
    def __str__(self) -> str: ...
    def to_dict(self) -> dict[str, int | str]: ...
    @classmethod
    def from_dict(cls, payload: Mapping[str, object]) -> Version: ...
    @classmethod
    def from_string(cls, value: str) -> Version: ...

INTERCHANGE_VERSION: Version

def manifest_path(interchange_dir: Path) -> Path: ...

def schema_with_version(schema: object, *, version: Version = ...) -> object: ...

def write_version_manifest(interchange_dir: Path, *, version: Version = ...) -> Path: ...

def read_version_manifest(interchange_dir: Path) -> Optional[Version]: ...

def needs_major_refresh(interchange_dir: Path, *, version: Version = ...) -> bool: ...

def remove_incompatible_interchange(interchange_dir: Path, *, version: Version = ...) -> bool: ...
