from __future__ import annotations

from .daymet_singlelocation_client import retrieve_historical_timeseries as retrieve_historical_timeseries
from .fast_single_point import single_point_extraction as single_point_extraction

daymet_proj4: str
