"""Add fs_uniquifier to User

Revision ID: 28e48afd0090
Revises:
Create Date: 2024-05-24 00:18:15.649762

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '28e48afd0090'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=64), nullable=True))

    # Populate fs_uniquifier for existing users
    conn = op.get_bind()
    conn.execute(
        text("""
        UPDATE "user"
        SET fs_uniquifier = substring(md5(random()::text) from 1 for 64)
        """)
    )

    # Alter column to not nullable and add unique constraint after population
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fs_uniquifier', nullable=False)
        batch_op.create_unique_constraint('uq_user_fs_uniquifier', ['fs_uniquifier'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_fs_uniquifier', type_='unique')
        batch_op.drop_column('fs_uniquifier')
    # ### end Alembic commands ###
