from flask import jsonify
from wepppy.weppcloud.routes import *

def register_blueprints(app):

    @app.route('/health')
    def health():
        return jsonify('OK')

    app.register_blueprint(rq_api_bp)
    app.register_blueprint(rq_jobinfo_bp)
    app.register_blueprint(security_logging_bp)
    app.register_blueprint(security_ui_bp)
    app.register_blueprint(unitizer_bp)
    app.register_blueprint(map_bp)
    app.register_blueprint(user_bp)
    app.register_blueprint(landuse_bp)
    app.register_blueprint(soils_bp)
    app.register_blueprint(climate_bp)
    app.register_blueprint(rhem_bp)
    app.register_blueprint(treatments_bp)
    app.register_blueprint(watar_bp)
    app.register_blueprint(watershed_bp)
    app.register_blueprint(wepp_bp)
    app.register_blueprint(run_0_bp)
    app.register_blueprint(weppcloud_site_bp)
    app.register_blueprint(admin_bp)
    app.register_blueprint(archive_bp)
    app.register_blueprint(command_bar_bp)
    app.register_blueprint(debris_flow_bp)
    app.register_blueprint(disturbed_bp)
    app.register_blueprint(export_bp)
    app.register_blueprint(geodata_bp)
    app.register_blueprint(diff_bp)
    app.register_blueprint(fork_bp)
    app.register_blueprint(observed_bp)
    app.register_blueprint(omni_bp)
    app.register_blueprint(pivottable_bp)
    app.register_blueprint(project_bp)
    app.register_blueprint(jsoncrack_bp)
    app.register_blueprint(rangeland_bp)
    app.register_blueprint(rangeland_cover_bp)
    app.register_blueprint(weppcloudr_bp)
    app.register_blueprint(locations_bp)
    app.register_blueprint(rq_job_dashboard_bp)
    app.register_blueprint(readme_bp)
    app.register_blueprint(usersum_bp)
    app.register_blueprint(stats_bp)
    app.register_blueprint(combined_watershed_viewer_bp)
    app.register_blueprint(batch_runner_bp)
    app.register_blueprint(interchange_bp)
