from __future__ import annotations

from collections import Counter
from collections.abc import Iterator
from typing import Dict, TypeVar

__all__ = ["RunStatistics"]

T_RunStatistics = TypeVar("T_RunStatistics", bound="RunStatistics")


class RunStatistics:
    wd: str
    _counter: Counter[str]

    def __init__(self, wd: str) -> None: ...
    def increment(self, cfg: str, num_hills: int | float = ..., increment_project: bool = ...) -> None: ...
    def increment_hillruns(self, cfg: str, num_hills: int | float) -> None: ...
    def increment_projects(self, cfg: str) -> None: ...
    def locked(self, validate_on_success: bool = ...) -> Iterator[None]: ...
    def dump_and_unlock(self, validate: bool = ...) -> None: ...
    @property
    def _lock(self) -> str: ...
    @property
    def _nodb(self) -> str: ...
    @property
    def _json(self) -> str: ...
    @property
    def counter(self) -> Dict[str, int]: ...
    def dump(self) -> None: ...
    def lock(self) -> None: ...
    def unlock(self, flag: str | None = ...) -> None: ...
    def islocked(self) -> bool: ...
    @classmethod
    def getInstance(cls: type[T_RunStatistics], wd: str) -> T_RunStatistics: ...


def _main() -> None: ...
