from __future__ import annotations

from pathlib import Path
from typing import Union


class InMemoryZip:
    def __init__(self) -> None: ...
    def append(self, filename_in_zip: str, file_contents: Union[str, bytes]) -> InMemoryZip: ...
    def read(self) -> bytes: ...
    def writetofile(self, filename: Union[str, Path]) -> None: ...
