from __future__ import annotations

class RDIOutOfBoundsException(Exception): ...

class RasterDatasetInterpolator:
    lon_lat: bool
    proj4: str
    left: float
    right: float
    upper: float
    lower: float

    def __init__(self, fname: str, proj: str | None = ...) -> None: ...

    def get_geo_coord(self, x: float, y: float) -> tuple[float, float]: ...

    def get_px_coord_from_lnglat(self, lng: float, lat: float) -> tuple[int, int]: ...

    def get_px_coord(self, e: float, n: float) -> tuple[float, float]: ...

    def get_nodata_value(self, band: int) -> float | None: ...

    @property
    def gt0_centroid(self) -> tuple[float, float]: ...

    @property
    def extent(self) -> tuple[float, float, float, float]: ...

    @property
    def width(self) -> int: ...

    @property
    def height(self) -> int: ...

    def __contains__(self, en: tuple[float, float]) -> bool: ...

    def get_location_info(
        self, lng: float, lat: float, method: str = ...
    ) -> float | list[float | None]: ...
