Attribute VB_Name = "Sheet17"
Attribute VB_Base = "0{00020820-0000-0000-C000-000000000046}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = True
Attribute VB_Control = "CommandButton12, 13, 0, MSForms, CommandButton"
Attribute VB_Control = "CommandButton10, 11, 1, MSForms, CommandButton"
Attribute VB_Control = "CommandButton9, 10, 2, MSForms, CommandButton"
Attribute VB_Control = "CommandButton8, 9, 3, MSForms, CommandButton"
Attribute VB_Control = "CommandButton7, 8, 4, MSForms, CommandButton"
Attribute VB_Control = "CommandButton1, 1, 5, MSForms, CommandButton"
Attribute VB_Control = "CommandButton2, 2, 6, MSForms, CommandButton"
Attribute VB_Control = "CommandButton3, 4, 7, MSForms, CommandButton"
Attribute VB_Control = "CommandButton4, 5, 8, MSForms, CommandButton"
Attribute VB_Control = "CommandButton5, 6, 9, MSForms, CommandButton"
Attribute VB_Control = "CommandButton6, 7, 10, MSForms, CommandButton"
Attribute VB_Control = "CommandButton11, 12, 11, MSForms, CommandButton"
Private Sub CommandButton1_Click()
 Module1.GotoTable
 
End Sub

Private Sub CommandButton10_Click()
 Module1.W5Help "W5CNAfterStorm.pdf"
End Sub

Private Sub CommandButton11_Click()
 Module1.W5Help "W5EffectiveCN.pdf"
End Sub

Private Sub CommandButton12_Click()
 Module1.W5Help "W5Ia.pdf"
End Sub

Private Sub CommandButton2_Click()
 Module1.GotoOutput
 
End Sub

Private Sub CommandButton3_Click()
 Module1.GotoMain
End Sub

Private Sub CommandButton4_Click()
 Module1.GotoTable
End Sub

Private Sub CommandButton5_Click()
 Module1.GotoMain
End Sub

Private Sub CommandButton6_Click()
 Module1.GotoOutput
End Sub

Private Sub CommandButton7_Click()
 Module1.W5Help "W5TransientStorage.pdf"
End Sub

Private Sub CommandButton8_Click()
 Module1.W5Help "W5MaxContArea.pdf"
End Sub

Private Sub CommandButton9_Click()
 Module1.W5Help "W5EFFLossRate.pdf"
End Sub
