"""Bounded, offline baseline/candidate WEPP soil-builder acceptance experiment.

Run through ``wctl run-python``; every generated file remains under --output.
This is a builder comparison, not a complete baseline application checkout.
Protected dependency bytes are compared to Git before their shared use. Only
incidental output clocks are fixed; no numerical field or generated byte is
normalized. The existing reclaimed fixture is synthetic, not a new SDA capture.
"""
from __future__ import annotations

import argparse
from contextlib import closing
import hashlib
import importlib
import importlib.metadata
import json
from pathlib import Path
import shutil
import socket
import sqlite3
import subprocess
import sys
from datetime import datetime, timezone

REPO = Path(__file__).resolve().parents[4]
BASE = "97800607c30c0979d422f99b1e2c65f1b8a89ab5"
SYNTHETIC = ("reclaimed", "missing_texture_defaults", "invalid_major_texture")
BUNDLED = {
    "historical_statsgo": ("wepppy/soils/ssurgo/data/statsgo/statsgo_tabular.db", [661787, 661951, 661956], True),
    "historical_ssurgo": ("wepppy/soils/ssurgo/data/surgo/surgo_tabular.db", [2396743], False),
}
PANELS = (*SYNTHETIC, *BUNDLED)
MODULES = ("wepppy.soils.ssurgo.ssurgo", "wepppy.nodb.core.wepp",
           "wepp_runner.wepp_runner")
FIXTURE = "tests/soils/test_ssurgo_reclaimed_fairpoint.py"


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def write_json(path, value):
    Path(path).write_text(json.dumps(value, indent=2, sort_keys=True,
                                    allow_nan=False) + "\n")


def git(*args):
    return subprocess.check_output(["git", *args], cwd=REPO)


def deny_network(event, args):
    if event == "socket.connect" and args[0].family in (socket.AF_INET, socket.AF_INET6):
        raise OSError("Network forbidden by frozen builder experiment")


class FixedDatetime(datetime):
    @classmethod
    def now(cls, tz=None):
        value = cls(2026, 9, 14, 12, tzinfo=timezone.utc)
        return value.replace(tzinfo=None) if tz is None else value.astimezone(tz)


def db_contents(path):
    with closing(sqlite3.connect(f"file:{path}?mode=ro", uri=True)) as conn:
        tables = conn.execute("SELECT name, sql FROM sqlite_master WHERE type='table' ORDER BY name").fetchall()
        return {name: {"schema": schema, "rows": sorted(conn.execute(
            f'SELECT * FROM "{name}"').fetchall(), key=repr)} for name, schema in tables}


def freeze_inputs(output):
    import pytest
    import wepppy.soils.ssurgo.ssurgo as module
    from tests.soils.test_ssurgo_reclaimed_fairpoint import (
        FAIRPOINT_MUKEYS, _install_reclaimed_fairpoint_fixture)

    inputs = output / "inputs"
    inputs.mkdir()
    cache = inputs / "reclaimed.sqlite"
    with pytest.MonkeyPatch.context() as patch:
        _install_reclaimed_fairpoint_fixture(patch)
        collection = module.SurgoSoilCollection(sorted(FAIRPOINT_MUKEYS), cache_db_path=str(cache))
        collection._disconnect()
    for panel in SYNTHETIC[1:]:
        path = inputs / f"{panel}.sqlite"
        shutil.copyfile(cache, path)
        with closing(sqlite3.connect(path)) as conn:
            if panel == "missing_texture_defaults":
                conn.execute("UPDATE chorizon SET sandtotal_r=NULL, claytotal_r=NULL WHERE cokey % 10 = 1")
            else:
                conn.execute("UPDATE chorizon SET sandtotal_r=0 WHERE cokey % 10 = 1")
            conn.commit()
    source_provenance = {}
    for panel, (relative, mukeys, statsgo) in BUNDLED.items():
        source = REPO / relative
        source_hash = digest(source)
        assert not Path(str(source) + "-wal").exists()
        path = inputs / f"{panel}.sqlite"
        empty = module.SurgoSoilCollection([], use_statsgo=statsgo, cache_db_path=str(path))
        empty._disconnect()
        with closing(sqlite3.connect(f"file:{source}?mode=ro", uri=True)) as original, closing(sqlite3.connect(path)) as target:
            original.execute("BEGIN")
            keysets = {"mukey": mukeys}
            for table, field in (("component", "mukey"), ("chorizon", "cokey"),
                                 ("corestrictions", "cokey"), ("chfrags", "chkey"),
                                 ("chtexturegrp", "chkey")):
                keys = keysets[field]
                rows = original.execute(f'SELECT * FROM "{table}" WHERE "{field}" IN ({",".join("?" for _ in keys)})', keys).fetchall()
                if rows:
                    target.executemany(f'INSERT INTO "{table}" VALUES ({",".join("?" for _ in rows[0])})', rows)
                if table in ("component", "chorizon"):
                    keysets["cokey" if table == "component" else "chkey"] = [row[1] for row in rows]
                bad = f"bad_{table}_{field}"
                rows = original.execute(f'SELECT * FROM "{bad}" WHERE "{field}" IN ({",".join("?" for _ in keys)})', keys).fetchall()
                target.executemany(f'INSERT INTO "{bad}" VALUES (?)', rows)
            target.commit()
        assert digest(source) == source_hash and not Path(str(source) + "-wal").exists()
        source_provenance[panel] = {"repository_path": relative, "sha256": source_hash,
                                    "selected_mukeys": mukeys, "use_statsgo": statsgo,
                                    "historical_version": "unknown; repository-bundled frozen database"}
    write_json(inputs / "bundled_source_provenance.json", source_provenance)
    inventory = {}
    for panel in PANELS:
        path = inputs / f"{panel}.sqlite"
        contents = db_contents(path)
        write_json(inputs / f"{panel}.json", contents)
        inventory[panel] = {"sha256": digest(path), "logical_sha256": digest(inputs / f"{panel}.json")}
    return inventory


def worker(output, revision):
    # Execute retained original module source in canonical namespaces, preserving
    # installed resource paths and process-pool pickle identities. Shared soil
    # dependencies have already passed the exact Git-byte equality gate.
    modules = {}
    for name in MODULES:
        module = importlib.import_module(name)
        source = output / "source" / revision / (name.replace(".", "/") + ".py")
        exec(compile(source.read_bytes(), module.__file__, "exec"), module.__dict__)
        modules[name] = module
    module = modules[MODULES[0]]
    module.datetime = FixedDatetime
    utility = importlib.import_module("wepppy.wepp.soils.utils.wepp_soil_util")
    utility.datetime = FixedDatetime
    from wepppy.nodb.mods.postfire_debris_flow.soil_policy import derive_recorded_component

    def forbidden_fetch(*args, **kwargs):
        raise AssertionError("Complete frozen cache must not fetch any missing records")

    for suffix in ("components", "chorizon", "corestrictions", "chfrags", "chtexturegrp"):
        setattr(module, "_fetch_" + suffix, forbidden_fetch)
    original_connect = sqlite3.connect

    def bounded_connect(database, *args, **kwargs):
        location = str(database).removeprefix("file:").split("?", 1)[0]
        if location != ":memory:" and not Path(location).resolve().is_relative_to(output):
            raise AssertionError(f"SQLite outside retained experiment: {location}")
        return original_connect(database, *args, **kwargs)

    sqlite3.connect = bounded_connect
    results = {}
    for panel in PANELS:
        for statsgo in ((BUNDLED[panel][2],) if panel in BUNDLED else (False, True)):
            key = f"{panel}/{'statsgo' if statsgo else 'ssurgo'}"
            case = output / revision / key
            soil_dir = case / "soils"
            soil_dir.mkdir(parents=True)
            cache = case / "tabular.sqlite"
            shutil.copyfile(output / "inputs" / f"{panel}.sqlite", cache)
            before = db_contents(cache)
            mukeys = BUNDLED[panel][1] if panel in BUNDLED else [3294459, 3294460, 3294461]
            collection = module.SurgoSoilCollection(
                mukeys, use_statsgo=statsgo, cache_db_path=str(cache))
            try:
                assert collection._sync_n == 0
                collection.makeWeppSoils(max_workers=1, verbose=True)
                assert not collection.getInValidWeppSoils()
                summaries = collection.writeWeppSoils(str(soil_dir), write_logs=True)
                soils = {}
                for index, mukey in enumerate(sorted(summaries), start=1):
                    soil = collection.weppSoils[mukey]
                    if panel in SYNTHETIC:
                        expected = mukey * 10 + (2 if panel == "invalid_major_texture" else 1)
                        assert soil.majorComponent.cokey == expected
                        assert soil.num_layers == 1 and soil.res_lyr_i == 1
                    raw_major = collection.get_layers(collection.get_components(mukey)[0]["cokey"])
                    depth = derive_recorded_component(raw_major)
                    if panel in SYNTHETIC:
                        assert depth["status"] == "valid" and depth["thickness_cm"] == 152
                    summary = summaries[mukey].__getstate__()
                    # This one source-directory location differs by case; retain
                    # the raw summary separately and compare its relative path.
                    write_json(soil_dir / f"{mukey}.summary.json", summary)
                    summary["soils_dir"] = "soils"
                    soils[str(mukey)] = dict(
                        summary=summary, selected_component=vars(soil.majorComponent),
                        horizons=[vars(horizon) for horizon in soil.horizons],
                        horizons_mask=soil.horizons_mask, num_layers=soil.num_layers,
                        restrictive_index=soil.res_lyr_i, restrictive_ksat=soil.res_lyr_ksat,
                        build_notes=soil.build_notes, build_log=soil.log,
                        raw_major_m3_depth=depth)
                    for treatment in ("default", "clip_and_kslast"):
                        runs = case / treatment / "wepp" / "runs"
                        runs.mkdir(parents=True, exist_ok=True)
                        clipped = treatment == "clip_and_kslast"
                        modules[MODULES[1]].prep_soil((
                            str(index * 10 + 1), str(soil_dir / summaries[mukey].fname),
                            str(runs / f"p{index}.sol"), 0.02 if clipped else None,
                            None, 0.6 if clipped else 0.75, clipped, 50.0, False, 0.0))
                        modules[MODULES[2]].make_hillslope_run(index, 30, str(runs), reveg=False)
                        run_text = (runs / f"p{index}.run").read_text()
                        assert f"p{index}.sol" in run_text
                results[key] = dict(source_data=collection.source_data, soils=soils)
            finally:
                collection._disconnect()
            assert db_contents(cache) == before
            artifacts = {str(path.relative_to(case)): digest(path) for path in sorted(case.rglob("*"))
                         if path.is_file() and not path.name.endswith((".summary.json", "-wal", "-shm"))}
            # The schema/committed rows are checked above. SQLite may remove or
            # rewrite empty WAL/shared-memory coordination files on connection
            # cleanup; those are not generated soil payloads or stable hashes.
            results[key]["cache_logical_unchanged"] = True
            results[key]["artifacts"] = artifacts
    write_json(output / revision / "results.json", results)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--worker", choices=("base", "candidate"))
    args = parser.parse_args()
    output = args.output.resolve()
    if not output.is_relative_to(Path(__file__).resolve().parent):
        raise ValueError("Output must be a visible directory under this work package's artifacts")
    sys.addaudithook(deny_network)
    if args.worker:
        worker(output, args.worker)
        return
    output.mkdir(exist_ok=False)
    paths = git("ls-tree", "-r", "--name-only", BASE, "wepppy/soils", "wepppy/wepp/soils",
                "wepppy/nodb/core/soils.py", "wepppy/nodb/core/wepp.py",
                "wepppy/nodb/core/wepp_prep_service.py", "wepp_runner").decode().splitlines()
    identities = {}
    for path in paths:
        if not (path.endswith(".py") or path.startswith("wepp_runner/templates/")):
            continue
        previous = git("show", f"{BASE}:{path}")
        current = (REPO / path).read_bytes()
        identities[path] = dict(base_sha256=hashlib.sha256(previous).hexdigest(), candidate_sha256=digest(REPO / path))
        if previous != current:
            write_json(output / "protected_identities.json", identities)
            raise AssertionError(f"Protected dependency changed: {path}")
    for revision in ("base", "candidate"):
        for name in MODULES:
            path = name.replace(".", "/") + ".py"
            target = output / "source" / revision / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(git("show", f"{BASE}:{path}") if revision == "base" else (REPO / path).read_bytes())
    write_json(output / "protected_identities.json", identities)
    inputs = freeze_inputs(output)
    import rosetta
    native = {}
    for name, loaded in sorted(sys.modules.items()):
        location = getattr(loaded, "__file__", None)
        if location and str(location).endswith(".so") and name.startswith(("numpy", "duckdb")):
            path = Path(location)
            native[name] = {"path": str(path), "sha256": digest(path)}
    rosetta_root = Path(rosetta.__file__).parent
    rosetta_files = {str(path.relative_to(rosetta_root)): digest(path)
                     for path in rosetta_root.rglob("*")
                     if path.is_file() and path.suffix in (".py", ".duckdb")}
    environment = dict(
        base=BASE, candidate_head=git("rev-parse", "HEAD").decode().strip(),
        validation_script_sha256=digest(__file__),
        python=sys.version, sqlite=sqlite3.sqlite_version,
        packages={name: importlib.metadata.version(name) for name in
                  ("numpy", "rasterio", "jsonpickle")},
        fixture={"path": FIXTURE, "sha256": digest(REPO / FIXTURE)},
        native_dependencies=native, rosetta_source_and_model_hashes=rosetta_files,
        input_hashes=inputs, fixed_output_clock="2026-09-14T12:00:00Z",
        method="Separate processes, retained baseline/candidate module sources, exact unchanged protected dependencies",
        network="Internet socket connects prohibited; no missing-record fetch allowed")
    write_json(output / "environment.json", environment)
    for revision in ("base", "candidate"):
        with (output / f"{revision}.log").open("w") as log:
            subprocess.run([sys.executable, str(Path(__file__).resolve()), "--output", str(output),
                            "--worker", revision], check=True, stdout=log, stderr=subprocess.STDOUT)
    baseline = json.loads((output / "base/results.json").read_text())
    candidate = json.loads((output / "candidate/results.json").read_text())
    comparisons = {key: baseline[key] == candidate[key] for key in baseline}
    retained_count = 0
    for revision, results in (("base", baseline), ("candidate", candidate)):
        for key, case in results.items():
            for relative, expected in case["artifacts"].items():
                assert digest(output / revision / key / relative) == expected
                retained_count += 1
    for panel in PANELS:
        assert digest(output / "inputs" / f"{panel}.sqlite") == inputs[panel]["sha256"]
    write_json(output / "comparison.json", dict(all_equal=all(comparisons.values()), cases=comparisons,
               builder_executions=16, generated_soils_per_revision=22,
               downstream_soils_per_revision=44, downstream_run_files_per_revision=44,
               input_databases_unchanged=True, retained_payload_hashes_rechecked=retained_count,
               sqlite_coordination_files="Excluded from payload hashes; committed schema/rows compared exactly"))
    assert all(comparisons.values()), "Parity difference: inspect retained results.json files"
    print(json.dumps(comparisons, indent=2))


if __name__ == "__main__":
    main()
