from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import pytest

pytest.importorskip("jinja2")
from jinja2 import Environment, FileSystemLoader, select_autoescape

pytestmark = pytest.mark.unit


def _render_report(*, warning: str | None) -> str:
    templates_dir = Path(__file__).resolve().parents[3] / "wepppy" / "weppcloud" / "templates"
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        autoescape=select_autoescape(("htm", "html")),
    )
    env.globals["url_for_run"] = lambda endpoint, **kwargs: (
        f"/runs/{kwargs.get('runid', 'run')}/{kwargs.get('config', 'cfg')}/{kwargs.get('subpath', '')}"
    )
    env.globals["unitizer"] = lambda value, _unit: f"{float(value):.2f}"
    env.globals["unitizer_units"] = lambda unit: unit
    env.globals["mean"] = lambda values: sum(values) / len(values)

    climate = SimpleNamespace(
        is_single_storm=False,
        ss_batch_storms=None,
        par_fn="ws.par",
        cli_fn="wepp.cli",
        observed_quality_guard_summary_warning=warning,
        monthlies=SimpleNamespace(
            ppts=[1.0] * 12,
            nwds=[10.0] * 12,
            tmaxs=[70.0] * 12,
            tmins=[40.0] * 12,
        ),
    )

    template = env.get_template("reports/climate.htm")
    return template.render(
        runid="test-run",
        config="main",
        station_meta=None,
        climate=climate,
        precip_frequency=None,
        atlas14_frequency=None,
    )


def test_climate_report_renders_observed_quality_guard_warning() -> None:
    warning = (
        "CLIGEN failed to converge, continuing because silent-pass is enabled. "
        "Try selecting different station or setting Adjust MX .5 P Values"
    )
    html = _render_report(warning=warning)

    assert "Summary for the climate generated by CLIGEN at watershed centroid" in html
    assert warning in html


def test_climate_report_omits_warning_block_when_not_set() -> None:
    html = _render_report(warning=None)

    assert "Summary for the climate generated by CLIGEN at watershed centroid" in html
    assert "continuing because silent-pass is enabled" not in html
