from __future__ import annotations

import logging
from enum import IntEnum
from typing import Any, ClassVar, Dict, Iterable, List, Optional, Set, Tuple

import pandas as pd

from wepppy.nodb.base import NoDbBase

__all__: list[str] = [
    "OMNI_REL_DIR",
    "LOGGER",
    "OmniScenario",
    "OmniNoDbLockedException",
    "Omni",
]

OMNI_REL_DIR: str
LOGGER: logging.Logger

ScenarioDef = Dict[str, Any]
ContrastMapping = Dict[int | str, str]
ScenarioDependency = Dict[str, Dict[str, Any]]
ContrastDependencies = Dict[str, Dict[str, Optional[str]]]
ContrastDependency = Dict[str, Dict[str, Any]]


class OmniScenario(IntEnum):
    UniformLow = ...
    UniformModerate = ...
    UniformHigh = ...
    Thinning = ...
    Mulch = ...
    SBSmap = ...
    Undisturbed = ...
    PrescribedFire = ...

    @staticmethod
    def parse(value: int | str | OmniScenario) -> OmniScenario: ...


class OmniNoDbLockedException(Exception):
    ...


def _clear_nodb_cache_and_locks(runid: str, pup_relpath: Optional[str] = ...) -> None: ...

def _run_contrast(
    contrast_id: str,
    contrast_name: str,
    contrasts: ContrastMapping,
    wd: str,
    runid: str,
    control_scenario_key: str,
    contrast_scenario_key: str,
    wepp_bin: str = ...,
    output_options: Dict[str, bool] | None = ...,
) -> str: ...

def _omni_clone(scenario_def: ScenarioDef, wd: str, runid: str) -> str: ...

def _omni_clone_sibling(new_wd: str, omni_clone_sibling_name: str, runid: str, parent_wd: str) -> None: ...

def _scenario_name_from_scenario_definition(scenario_def: ScenarioDef) -> str: ...

def _hash_file_sha1(path: Optional[str]) -> Optional[str]: ...


class Omni(NoDbBase):
    filename: ClassVar[str]
    __name__: ClassVar[str]
    __exclude__: ClassVar[Tuple[str, ...]]

    def __new__(cls, *args: object, **kwargs: object) -> Omni: ...

    def __init__(
        self,
        wd: str,
        cfg_fn: str = ...,
        run_group: Optional[str] = ...,
        group_name: Optional[str] = ...,
    ) -> None: ...

    def __getstate__(self) -> dict[str, Any]: ...

    def __setstate__(self, state: dict[str, Any]) -> None: ...

    @property
    def scenarios(self) -> List[ScenarioDef]: ...

    @scenarios.setter
    def scenarios(self, value: List[ScenarioDef]) -> None: ...

    @property
    def scenario_dependency_tree(self) -> ScenarioDependency: ...

    @scenario_dependency_tree.setter
    def scenario_dependency_tree(self, value: ScenarioDependency) -> None: ...

    @property
    def scenario_run_state(self) -> List[Dict[str, Any]]: ...

    @scenario_run_state.setter
    def scenario_run_state(self, value: List[Dict[str, Any]]) -> None: ...

    def parse_scenarios(self, parsed_inputs: Iterable[Tuple[OmniScenario, ScenarioDef]]) -> None: ...

    def delete_scenarios(self, scenario_names: Iterable[str]) -> Dict[str, List[str]]: ...

    def parse_inputs(self, kwds: Dict[str, Any]) -> None: ...

    @property
    def contrasts(self) -> Optional[List[ContrastMapping]]: ...

    @contrasts.setter
    def contrasts(self, value: Optional[List[ContrastMapping]]) -> None: ...

    @property
    def contrast_names(self) -> Optional[List[Optional[str]]]: ...

    @contrast_names.setter
    def contrast_names(self, value: Optional[List[Optional[str]]]) -> None: ...

    @property
    def contrast_dependency_tree(self) -> ContrastDependency: ...

    @contrast_dependency_tree.setter
    def contrast_dependency_tree(self, value: ContrastDependency) -> None: ...

    @property
    def contrast_batch_size(self) -> int: ...

    @contrast_batch_size.setter
    def contrast_batch_size(self, value: Optional[int]) -> None: ...

    @property
    def control_scenario(self) -> Optional[str]: ...

    @control_scenario.setter
    def control_scenario(self, value: Optional[str]) -> None: ...

    @property
    def contrast_scenario(self) -> Optional[str]: ...

    @contrast_scenario.setter
    def contrast_scenario(self, value: Optional[str]) -> None: ...

    @property
    def contrast_object_param(self) -> Optional[str]: ...

    @contrast_object_param.setter
    def contrast_object_param(self, value: Optional[str]) -> None: ...

    @property
    def contrast_cumulative_obj_param_threshold_fraction(self) -> Optional[float]: ...

    @contrast_cumulative_obj_param_threshold_fraction.setter
    def contrast_cumulative_obj_param_threshold_fraction(self, value: Optional[float]) -> None: ...

    @property
    def contrast_hillslope_limit(self) -> Optional[int]: ...

    @contrast_hillslope_limit.setter
    def contrast_hillslope_limit(self, value: Optional[int]) -> None: ...

    @property
    def contrast_hill_min_slope(self) -> Optional[float]: ...

    @contrast_hill_min_slope.setter
    def contrast_hill_min_slope(self, value: Optional[float]) -> None: ...

    @property
    def contrast_hill_max_slope(self) -> Optional[float]: ...

    @contrast_hill_max_slope.setter
    def contrast_hill_max_slope(self, value: Optional[float]) -> None: ...

    @property
    def contrast_select_burn_severities(self) -> Optional[List[int]]: ...

    @contrast_select_burn_severities.setter
    def contrast_select_burn_severities(self, value: Optional[List[int]]) -> None: ...

    @property
    def contrast_select_topaz_ids(self) -> Optional[List[int]]: ...

    @contrast_select_topaz_ids.setter
    def contrast_select_topaz_ids(self, value: Optional[List[int]]) -> None: ...

    @property
    def contrast_selection_mode(self) -> Optional[str]: ...

    @contrast_selection_mode.setter
    def contrast_selection_mode(self, value: Optional[str]) -> None: ...

    @property
    def contrast_geojson_path(self) -> Optional[str]: ...

    @contrast_geojson_path.setter
    def contrast_geojson_path(self, value: Optional[str]) -> None: ...

    @property
    def contrast_geojson_name_key(self) -> Optional[str]: ...

    @contrast_geojson_name_key.setter
    def contrast_geojson_name_key(self, value: Optional[str]) -> None: ...

    @property
    def contrast_hillslope_groups(self) -> Optional[Any]: ...

    @contrast_hillslope_groups.setter
    def contrast_hillslope_groups(self, value: Optional[Any]) -> None: ...

    @property
    def contrast_order_reduction_passes(self) -> Optional[int]: ...

    @contrast_order_reduction_passes.setter
    def contrast_order_reduction_passes(self, value: Optional[int]) -> None: ...

    @property
    def contrast_pairs(self) -> List[Dict[str, str]]: ...

    @contrast_pairs.setter
    def contrast_pairs(self, value: List[Dict[str, str]]) -> None: ...

    @property
    def contrast_output_chan_out(self) -> bool: ...

    @contrast_output_chan_out.setter
    def contrast_output_chan_out(self, value: bool) -> None: ...

    @property
    def contrast_output_tcr_out(self) -> bool: ...

    @contrast_output_tcr_out.setter
    def contrast_output_tcr_out(self, value: bool) -> None: ...

    @property
    def contrast_output_chnwb(self) -> bool: ...

    @contrast_output_chnwb.setter
    def contrast_output_chnwb(self, value: bool) -> None: ...

    @property
    def contrast_output_soil_pw0(self) -> bool: ...

    @contrast_output_soil_pw0.setter
    def contrast_output_soil_pw0(self, value: bool) -> None: ...

    @property
    def contrast_output_plot_pw0(self) -> bool: ...

    @contrast_output_plot_pw0.setter
    def contrast_output_plot_pw0(self, value: bool) -> None: ...

    @property
    def contrast_output_ebe_pw0(self) -> bool: ...

    @contrast_output_ebe_pw0.setter
    def contrast_output_ebe_pw0(self, value: bool) -> None: ...

    def contrast_output_options(self) -> Dict[str, bool]: ...

    @property
    def omni_dir(self) -> str: ...

    def get_objective_parameter_from_gpkg(self, objective_parameter: str, scenario: Optional[str] = ...) -> Tuple[List[Any], float]: ...

    def clear_contrasts(self) -> None: ...

    def _clean_contrast_runs(self) -> None: ...

    def _clean_stale_contrast_runs(self, active_ids: Iterable[int]) -> None: ...

    def _clean_contrast_run(self, contrast_id: int) -> None: ...

    def _contrast_sidecar_dir(self) -> str: ...

    def _contrast_sidecar_path(self, contrast_id: int) -> str: ...

    def _contrast_build_report_path(self) -> str: ...

    def _contrast_ids_geojson_path(self) -> str: ...

    def _load_contrast_build_report(self) -> List[Dict[str, Any]]: ...

    def _load_contrast_sidecar(self, contrast_id: int) -> ContrastMapping: ...

    def _write_contrast_sidecar(self, contrast_id: int, contrast: ContrastMapping) -> str: ...

    def _contrast_run_readme_path(self, contrast_id: int) -> str: ...

    def _normalize_landuse_key(self, value: Any) -> Optional[str]: ...
    def _normalize_landuse_key_impl(self, value: Any) -> Optional[str]: ...

    def _load_landuse_key_map(self, landuse_wd: str) -> Optional[Dict[int, Optional[str]]]: ...
    def _load_landuse_key_map_impl(self, landuse_wd: str) -> Optional[Dict[int, Optional[str]]]: ...

    def _contrast_landuse_skip_reason(
        self,
        contrast_id: int,
        contrast_name: str,
        *,
        landuse_cache: Optional[Dict[str, Optional[Dict[int, Optional[str]]]]] = ...,
    ) -> Optional[str]: ...
    def _contrast_landuse_skip_reason_impl(
        self,
        contrast_id: int,
        contrast_name: str,
        *,
        landuse_cache: Optional[Dict[str, Optional[Dict[int, Optional[str]]]]] = ...,
    ) -> Optional[str]: ...

    def _scenario_run_readme_path(self, scenario_name: Optional[Any]) -> str: ...

    def _normalize_contrast_pairs(self, value: Any) -> List[Dict[str, str]]: ...

    def _redisprep_snapshot(self, path: str) -> Optional[Dict[str, Any]]: ...

    def _normalize_contrast_redisprep_snapshot(
        self, snapshot: Optional[Dict[str, Any]]
    ) -> Optional[Dict[str, Any]]: ...

    def _scenario_redisprep_snapshot(self, scenario_key: str) -> Optional[Dict[str, Any]]: ...

    def _contrast_scenario_keys(self, contrast_name: str) -> Tuple[str, str]: ...
    def _contrast_scenario_keys_impl(self, contrast_name: str) -> Tuple[str, str]: ...

    def _contrast_run_status(self, contrast_id: int, contrast_name: str) -> str: ...

    def _contrast_dependency_entry(self, contrast_id: int, contrast_name: str) -> Dict[str, Any]: ...

    def _update_contrast_dependency_tree(
        self,
        contrast_name: str,
        dependency_entry: Dict[str, Any],
        *,
        max_tries: int = ...,
        delay: float = ...,
    ) -> None: ...

    def _remove_contrast_dependency_entry(
        self,
        contrast_name: str,
        *,
        max_tries: int = ...,
        delay: float = ...,
    ) -> None: ...

    def build_contrasts(
        self,
        control_scenario_def: Optional[ScenarioDef],
        contrast_scenario_def: Optional[ScenarioDef],
        obj_param: str = ...,
        contrast_cumulative_obj_param_threshold_fraction: float = ...,
        contrast_hillslope_limit: Optional[int] = ...,
        hill_min_slope: Optional[float] = ...,
        hill_max_slope: Optional[float] = ...,
        select_burn_severities: Optional[List[int]] = ...,
        select_topaz_ids: Optional[List[int]] = ...,
        contrast_pairs: Optional[List[Dict[str, str]]] = ...,
    ) -> None: ...

    @property
    def base_scenario(self) -> OmniScenario: ...

    def _build_contrasts(self) -> None: ...

    def _build_contrast_ids_geojson(self) -> Optional[str]: ...

    def _resolve_order_reduction_passes(self) -> int: ...

    def _build_contrasts_stream_order(self) -> None: ...

    def _build_contrasts_user_defined_areas(self) -> None: ...

    def _build_contrasts_user_defined_hillslope_groups(self) -> None: ...

    def build_contrasts_dry_run_report(
        self,
        control_scenario_def: Optional[ScenarioDef],
        contrast_scenario_def: Optional[ScenarioDef],
        obj_param: str = ...,
        contrast_cumulative_obj_param_threshold_fraction: float = ...,
        contrast_hillslope_limit: Optional[int] = ...,
        hill_min_slope: Optional[float] = ...,
        hill_max_slope: Optional[float] = ...,
        select_burn_severities: Optional[List[int]] = ...,
        select_topaz_ids: Optional[List[int]] = ...,
        contrast_pairs: Optional[List[Dict[str, str]]] = ...,
    ) -> Dict[str, Any]: ...

    def contrast_status_report(self) -> Dict[str, Any]: ...

    def run_omni_contrasts(self) -> None: ...

    def run_omni_contrast(self, contrast_id: int, *, rq_job_id: Optional[str] = ...) -> str: ...

    def contrasts_report(self) -> pd.DataFrame: ...

    def _normalize_scenario_key(self, name: Optional[Any]) -> str: ...
    def _normalize_scenario_key_impl(self, name: Optional[Any]) -> str: ...

    def _loss_pw0_path_for_scenario(self, scenario_name: Optional[Any]) -> str: ...
    def _loss_pw0_path_for_scenario_impl(self, scenario_name: Optional[Any]) -> str: ...

    def _interchange_class_data_path_for_scenario(self, scenario_name: Optional[Any]) -> str: ...

    def _interchange_class_data_path_for_scenario_impl(self, scenario_name: Optional[Any]) -> str: ...

    def _year_set_for_scenario(self, scenario_name: Optional[Any]) -> Optional[Set[int]]: ...

    def _year_set_for_scenario_impl(self, scenario_name: Optional[Any]) -> Optional[Set[int]]: ...

    def _scenario_signature(self, scenario_def: ScenarioDef) -> str: ...
    def _scenario_signature_impl(self, scenario_def: ScenarioDef) -> str: ...

    def _scenario_dependency_target(self, scenario: OmniScenario, scenario_def: ScenarioDef) -> Optional[str]: ...
    def _scenario_dependency_target_impl(self, scenario: OmniScenario, scenario_def: ScenarioDef) -> Optional[str]: ...

    def _contrast_dependencies(self, contrast_name: str) -> ContrastDependencies: ...
    def _contrast_dependencies_impl(self, contrast_name: str) -> ContrastDependencies: ...

    def _contrast_signature(self, contrast_name: str, contrast_payload: ContrastMapping) -> str: ...

    def _contrast_pair_signature(self, control_key: str, contrast_key: str, area_label: str) -> str: ...

    def _load_user_defined_signature_map(self) -> Dict[str, int]: ...

    def _load_user_defined_hillslope_group_signature_map(self) -> Dict[str, int]: ...

    def _post_omni_run(self, omni_wd: str, scenario_name: str) -> None: ...

    @property
    def ran_scenarios(self) -> List[str]: ...

    def scenario_run_markers(self) -> Dict[str, bool]: ...

    @property
    def use_rq_job_pool_concurrency(self) -> bool: ...

    @use_rq_job_pool_concurrency.setter
    def use_rq_job_pool_concurrency(self, value: bool) -> None: ...

    @property
    def rq_job_pool_max_worker_per_scenario_task(self) -> int: ...

    def run_omni_scenarios(self) -> None: ...

    def run_omni_scenario(self, scenario_def: ScenarioDef) -> Tuple[str, str]: ...

    @property
    def has_ran_scenarios(self) -> bool: ...

    @property
    def has_ran_contrasts(self) -> bool: ...

    def scenarios_report(self) -> pd.DataFrame: ...

    def compile_hillslope_summaries(self) -> pd.DataFrame: ...

    def compile_channel_summaries(self) -> pd.DataFrame: ...
