import os
from typing import ContextManager

__all__ = ["initial_read_retry", "read_retry_active", "read_text", "read_text_snapshot", "stat_path"]

def initial_read_retry(*, runid: str, job_id: str) -> ContextManager[None]: ...
def read_retry_active() -> bool: ...
def read_text(path: str, *, allow_missing: bool = ...) -> str | None: ...
def stat_path(path: str, *, allow_missing: bool = ...) -> os.stat_result | None: ...

def read_text_snapshot(path: str, *, allow_missing: bool = ...) -> tuple[str, os.stat_result] | None: ...
