"""BatchRunner public API; validate with wctl run-stubtest wepppy.nodb.batch_runner."""

from __future__ import annotations

import logging
from typing import Any, ClassVar, Dict, Iterable, List, Mapping, NoReturn, Optional, Tuple

from wepppy.topo.watershed_collection import WatershedCollection, WatershedFeature
from .base import NoDbBase
from .redis_prep import RedisPrep, TaskEnum

__all__ = ["BatchRunner"]


class BatchRunner(NoDbBase):
    __name__: ClassVar[str]
    filename: ClassVar[str]
    RESOURCE_WATERSHED: ClassVar[str]
    DEFAULT_TASKS: ClassVar[Tuple[TaskEnum, ...]]
    RUN_METADATA_FILENAME: ClassVar[str]
    OPTIONAL_TASK_NODB_FILENAMES: ClassVar[Dict[TaskEnum, str]]
    BASE_PROJECT_RESYNC_RULES: ClassVar[Dict[str, Dict[str, Any]]]

    def __init__(self, wd: str, batch_config: str, base_config: str) -> None: ...

    def __getstate__(self) -> Dict[str, Any]: ...

    @property
    def run_directives(self) -> Dict[TaskEnum, bool]: ...

    def is_task_enabled(self, task: TaskEnum) -> bool: ...

    @property
    def rq_job_ids(self) -> Dict[str, str]: ...

    def set_rq_job_id(self, key: str, job_id: Optional[str]) -> None: ...

    def set_rq_job_id_fresh(self, key: str, job_id: Optional[str]) -> None: ...

    def update_run_directives(self, directives: Mapping[str, Any]) -> Dict[TaskEnum, bool]: ...

    def run_batch_hillslopes(self, watershed_feature: WatershedFeature, job_id: Optional[str] = ...) -> Tuple[str, ...]: ...

    def run_batch_watershed(self, watershed_feature: WatershedFeature, job_id: Optional[str] = ...) -> None: ...

    def run_batch_project(self, watershed_feature: WatershedFeature, job_id: Optional[str] = ...) -> Tuple[str, ...]: ...

    def clear_retry_runtime_locks(self, watershed_features: Iterable[WatershedFeature]) -> List[Dict[str, Any]]: ...

    @property
    def batch_name(self) -> str: ...

    @classmethod
    def getInstanceFromRunID(cls, runid: str, allow_nonexistent: bool = ..., ignore_lock: bool = ...) -> NoReturn: ...

    @classmethod
    def getInstanceFromBatchName(cls, batch_name: str) -> BatchRunner: ...

    @property
    def sbs_map(self) -> Optional[str]: ...

    @sbs_map.setter
    def sbs_map(self, value: Optional[str]) -> None: ...

    @property
    def sbs_map_metadata(self) -> Optional[Dict[str, Any]]: ...

    @sbs_map_metadata.setter
    def sbs_map_metadata(self, value: Optional[Dict[str, Any]]) -> None: ...

    def apply_sbs_resource_update(self, *, sbs_map: Any = ..., metadata: Any = ...) -> None: ...

    @property
    def base_wd(self) -> str: ...

    @property
    def base_config(self) -> Optional[str]: ...

    @base_config.setter
    def base_config(self, value: Optional[str]) -> None: ...

    @property
    def batch_runs_dir(self) -> str: ...

    @property
    def resources_dir(self) -> str: ...

    @property
    def logs_dir(self) -> str: ...

    def register_geojson(self, watershed_collection: WatershedCollection, metadata: Optional[Dict[str, Any]] = ...) -> None: ...

    def get_watershed_collection(self) -> WatershedCollection: ...

    def get_watershed_features_lpt(self) -> List[WatershedFeature]: ...

    @property
    def geojson_state(self) -> Optional[Dict[str, Any]]: ...

    @property
    def runid_template_state(self) -> Optional[Dict[str, Any]]: ...

    @runid_template_state.setter
    def runid_template_state(self, value: Optional[Dict[str, Any]]) -> None: ...

    def resync_base_project_attributes(self, run_wd: str, prep: RedisPrep, logger: logging.Logger) -> Dict[str, Any]: ...

    def classify_batch_run_state(self, watershed_feature: WatershedFeature) -> Dict[str, Any]: ...

    def classify_batch_run_states(self, watershed_features: Optional[Iterable[WatershedFeature]] = ...) -> Dict[str, Dict[str, Any]]: ...

    def retry_eligible_watershed_features(self, watershed_features: Optional[Iterable[WatershedFeature]] = ...) -> List[WatershedFeature]: ...

    def summarize_batch_run_states(self, states: Mapping[str, Mapping[str, Any]]) -> Dict[str, int]: ...

    def generate_runstate_report(self) -> Dict[str, Any]: ...

    def state_dict(self) -> Dict[str, Any]: ...

    def sbs_resource_state(self) -> Optional[Dict[str, Any]]: ...

    def generate_runstate_cli_report(self) -> str: ...
