from typing import Mapping, Protocol
from wepppy.project_config_serialization import CanonicalValue
__all__ = ["CapabilityConfig", "SOIL_BUILDER_MODES", "capability_ids", "resolve_named_preset_capabilities", "runtime_value_allowed", "soil_capability_modes"]
class CapabilityConfig(Protocol):
    def config_get_list(self, section: str, option: str, default: object = ...) -> object: ...
    def config_get_raw(self, section: str, option: str, default: object = ...) -> object: ...
SOIL_BUILDER_MODES: Mapping[str, int]
def capability_ids(config: CapabilityConfig, option: str) -> frozenset[str] | None: ...
def runtime_value_allowed(config: CapabilityConfig, option: str, value: object, *, stable_to_runtime: Mapping[str, object] | None = ...) -> bool: ...
def soil_capability_modes(config: CapabilityConfig) -> frozenset[int] | None: ...
def resolve_named_preset_capabilities(config: Mapping[str, Mapping[str, CanonicalValue]]) -> dict[str, CanonicalValue]: ...
