from = "_defaults"

[general]
name = "pep"
cellsize=30
w3w_api_key = "xbl7lv7i"

[topaz]
mcl=100
csa=10
zoom_min=11

[landuse]
enable_landuse_change=true

[soils]
wepp_chn_type  = "onrock 2"

[map]
center0 = [40.0, -99.0]
zoom0 = 3

[nodb]
mods = ["baer", "debris_flow"]

[climate]
observed_clis_wc = None
future_clis_wc = None
daymet_observed  = "daymet"

[wepp]
wepp_ui = false

[phosphorus_opts]
surf_runoff = None
lateral_flow = None
baseflow = None
sediment = None