from = "_defaults"

[general]
name = "disturbed"
cellsize=30

[unitizer]
is_english=true

[topaz]
mcl=60
csa=5
zoom_min=11

[landuse]
enable_landuse_change=true
mapping  = "disturbed"

[soils]
wepp_chn_type  = "default"

[map]
center0 = [40.0, -99.0]
zoom0 = 3

[nodb]
mods = ["disturbed", "debris_flow", "ash"]

[climate]
observed_clis_wc = None
future_clis_wc = None
daymet_observed  = "daymet/v4"

[wepp]
bin = "latest"
wepp_ui=true
pmet=true
frost=false
tcr=true
baseflow=true
snow=true
channel_erodibility=1E-6
channel_critical_shear=19.0
channel_2006_avke=10.0
multi_ofe=false
pmet_kcb=0.55
pmet_rawp=0.6
kslast=0.01

[tcr_opts]
taumin=20
taumax=190
kch=0.0005
nch=1.0

[snow_opts]
rst=0
newsnw=100.0
ssd=250.0

[phosphorus_opts]
surf_runoff = 0.007
lateral_flow = 0.008
baseflow = 0.009
sediment = 3000
