from = "_defaults"

[general]
name = "disturbedi-hi"
cellsize=30
locales=["hawaii",]

[unitizer]
is_english=true

[topaz]
mcl=100
csa=10
zoom_min=11

[landuse]
enable_landuse_change=true
mapping  = "disturbed"
nlcd_db = "hawaii/nlcd/latest"

[soils]
ssurgo_db = "hawaii/ssurgo"
wepp_chn_type  = "default"

[map]
center0 = [20.5, -157.5]
zoom0 = 7

[nodb]
mods = ["disturbed", "debris_flow", "ash"]

[climate]
cligen_db = "ghcn_stations.db"
observed_clis_wc = None
future_clis_wc = None
daymet_observed  = "daymet/v4"

[wepp]
wepp_ui = true
bin = "latest"
snow=true

[snow_opts]
rst=0
newsnw=100.0
ssd=250.0

[phosphorus_opts]
surf_runoff = None
lateral_flow = None
baseflow = None
sediment = None
