from = "_defaults"

[general]
name = "disturbed"
cellsize=30

[unitizer]
is_english=false

[topaz]
mcl=100
csa=10
zoom_min=12

[landuse]
enable_landuse_change = "trye"
sbs_map  = "/home/helen/geodata/fire_data/gaviotafire2004/2004/ca3448712019620040605_20040425_20050412_dnbr6.tif"
mapping  = "disturbed"

[soils]
wepp_chn_type  = "default"

[map]
center0 = [40.0, -99.0]
zoom0 = 3

[nodb]
mods = ["disturbed"]

[climate]
observed_clis_wc = None
future_clis_wc = None

[wepp]
wepp_ui = true
bin = "latest"
snow=true