from = "_defaults"

[general]
name = "seattle"
cellsize=30

[topaz]
mcl=60
csa=5
zoom_min=11

[landuse]
enable_landuse_change=true
sbs_map  = "None"
cover_defaults = "mods_dir/locations/general/lt_cover_defaults.csv"

[soils]

[map]
center0 = [40.0, -99.0]
zoom0 = 3

[nodb]
mods = ["general"]
lc_lookup_fn = "landSoilLookup.csv"

[climate]
observed_clis_wc = None
future_clis_wc = None

[phosphorus_opts]
surf_runoff = 0.003
lateral_flow = 0.004
baseflow = 0.005
sediment = 1000

[snow_opts]
rst=-2
newsnw=100
ssd=250.0

[wepp]
bin = "wepp_bd16b69"
snow=true
