from = "_defaults"

[general]
name = "us"
cellsize=30

[unitizer]
is_english=true

[topaz]
mcl=60
csa=5
zoom_min=11

[landuse]
enable_landuse_change=false
mapping  = "palouse"
sbs_map  = "None"

[soils]

[map]
center0 = [46.7, -117.0]
zoom0 = 10

[nodb]
mods = []

[climate]
observed_clis_wc = None
future_clis_wc = None

[phosphorus_opts]
surf_runoff = None
lateral_flow = None
baseflow = None
sediment = None

[wepp]
wepp_ui=true
bin = "latest"
