from dataclasses import dataclass
from typing import Mapping, Protocol

__all__ = ["CREATION_IDEMPOTENCY_TTL_SECONDS", "CreationIdempotencyError", "CreationReservation", "build_creation_fingerprint", "complete_creation", "release_creation", "reserve_creation"]
CREATION_IDEMPOTENCY_TTL_SECONDS: int

class RedisIdempotencyClient(Protocol):
    def set(self, key: str, value: str, *, nx: bool = ..., xx: bool = ..., ex: int = ...) -> object: ...
    def get(self, key: str) -> object: ...
    def delete(self, key: str) -> object: ...

class CreationIdempotencyError(ValueError): ...

@dataclass(frozen=True, slots=True)
class CreationReservation:
    status: str
    redis_key: str
    fingerprint: str
    reservation_token: str | None = ...
    run_id: str | None = ...
    location: str | None = ...

def build_creation_fingerprint(*, mode: str, preset_id: str, normalized_overrides: Mapping[str, object], registry_revision: str) -> str: ...
def reserve_creation(client: RedisIdempotencyClient, *, idempotency_key: str, actor_scope: str | None, fingerprint: str) -> CreationReservation: ...
def complete_creation(client: RedisIdempotencyClient, reservation: CreationReservation, *, run_id: str, location: str) -> None: ...
def release_creation(client: RedisIdempotencyClient, reservation: CreationReservation) -> None: ...
