- workflow_slug: archive-us-small
  title: US Small
  playback_type: archive
  profile_slug: us-small-wbt-daymet-rap-wepp
  playback_options: []
  schedule_pt: 05:05
  artifact_name: us-small-profile-archive-log
  artifact_path: telemetry/us-small-profile-archive.log
  description: Archive test of the US Small Watershed
  
- workflow_slug: fork-rattlesnake-undisturbify
  title: Rattlesnake (Undisturbify)
  playback_type: fork
  profile_slug: rattlesnake-topaz-vanilla-wepp-watar
  playback_options:
  - --undisturbify
  schedule_pt: 05:15
  artifact_name: rattlesnake-profile-fork-log
  artifact_path: telemetry/rattlesnake-profile-fork.log
  description: Undisturbify fork test of Rattlesnake

- workflow_slug: fork-us-small
  title: US Small
  playback_type: fork
  profile_slug: us-small-wbt-daymet-rap-wepp
  playback_options: []
  schedule_pt: 04:55
  artifact_name: us-small-profile-fork-log
  artifact_path: telemetry/us-small-profile-fork.log
  description: Fork test of the US Small Watershed

- workflow_slug: run-10m-mofe
  title: 10m MOFE
  playback_type: run
  profile_slug: topaz-10m-mofe
  playback_options: []
  schedule_pt: 03:30
  artifact_name: ten-meter-mofe-profile-run-log
  artifact_path: telemetry/ten-meter-mofe-profile-run.log
  description: Small Undisturbed US Watershed with TOPAZ Delineation and Multiple
    OFEs

- workflow_slug: run-earth-small
  title: Earth Small
  playback_type: run
  profile_slug: earth-in-bc-ca-w-daymet
  playback_options: []
  schedule_pt: 05:25
  artifact_name: earth-small-profile-run-log
  artifact_path: telemetry/earth-small-profile-run.log
  description: Earth OpenTopography API with ISRIC soil building, DAYMET in Canada,
    GHCN station DB

- workflow_slug: run-europe-disturbed
  title: Europe-Disturbed
  playback_type: run
  profile_slug: eu-ebos-heuristic-multiple
  playback_options: []
  schedule_pt: 03:40
  artifact_name: europe-disturbed-profile-run-log
  artifact_path: telemetry/europe-disturbed-profile-run.log
  description: Europe with eu-disturbed config and E-OBS multiple climates

- workflow_slug: run-australia-disturbed
  title: Australia-Disturbed
  playback_type: run
  profile_slug: au-disturbed
  playback_options: []
  schedule_pt: 03:50
  artifact_name: australia-disturbed-profile-run-log
  artifact_path: telemetry/australia-disturbed-profile-run.log
  description: Australia with au-disturbed config and vanilla climate

- workflow_slug: run-nexrad-prism-debrisflow
  title: NEXRAD (PRISM) DebrisFlow
  playback_type: run
  profile_slug: baer-cropped-wbt-nexrad-prism-rap-wepp-debrisflow
  playback_options: []
  schedule_pt: 04:00
  artifact_name: nexrad-prism-debrisflow-profile-run-log
  artifact_path: telemetry/nexrad-prism-debrisflow-profile-run.log
  description: Cameron Peak (baer.cropped.tif) WBT NEXRAD, RAP, WEPP, DebrisFlow

- workflow_slug: run-portland-disturbed
  title: Portland Disturbed
  playback_type: run
  profile_slug: small-daymet-portland
  playback_options: []
  schedule_pt: 03:10
  artifact_name: portland-disturbed-profile-run-log
  artifact_path: telemetry/portland-disturbed-profile-run.log
  description: Small Portland with Daymet

- workflow_slug: run-rattlesnake
  title: Rattlesnake
  playback_type: run
  profile_slug: rattlesnake-topaz-vanilla-wepp-watar
  playback_options: []
  schedule_pt: 04:30
  artifact_name: rattlesnake-profile-run-log
  artifact_path: telemetry/rattlesnake-profile-run.log
  description: Playback test of Rattlesnake - TOPAZ, Vanilla Cligent, WEPP, WATAR
    (Alex)

- workflow_slug: run-rhem
  title: RHEM
  playback_type: run
  profile_slug: us-rap-rhem
  playback_options: []
  schedule_pt: 04:20
  artifact_name: rhem-profile-run-log
  artifact_path: telemetry/rhem-profile-run.log
  description: Small US RHEM run with rangeland-cover from RAP

- workflow_slug: run-sbs-noct
  title: SBS NoCT
  playback_type: run
  profile_slug: eaton-noct-gridmet-wepp-2chaninp-watar-anu
  playback_options: []
  schedule_pt: 05:35
  artifact_name: sbs-noct-profile-run-log
  artifact_path: telemetry/sbs-noct-profile-run.log
  description: Eaton Fire (no CT), GRIDMET, WEPP, 2 channels of interest, WATAR (Anurag)

- workflow_slug: run-sbs-wbt-mofe
  title: SBS WBT MOFE
  playback_type: run
  profile_slug: rattlesnake-wbt-fill-mofe-daymet-wepp-watar
  playback_options: []
  schedule_pt: 03:15
  artifact_name: sbs-wbt-mofe-profile-run-log
  artifact_path: telemetry/sbs-wbt-mofe-profile-run.log
  description: Rattlesnake SBS with WBT (fill) Multiple OFEs, DAYMET, WEPP, WATAR
    (Anu)

- workflow_slug: run-seattle-simfire
  title: Seattle Simfire
  playback_type: run
  profile_slug: seattle-simfire-future-cli
  playback_options: []
  schedule_pt: 03:00
  artifact_name: seattle-simfire-profile-run-log
  artifact_path: telemetry/seattle-simfire-profile-run.log
  description: Seattle Simfire with Future Climate (NMME)

- workflow_slug: run-us-small
  title: US Small
  playback_type: run
  profile_slug: us-small-wbt-daymet-rap-wepp
  playback_options: []
  schedule_pt: 04:45
  artifact_name: us-small-profile-run-log
  artifact_path: telemetry/us-small-profile-run.log
  description: Playback test of the US Small Watershed (WBT, Daymet RAP, WEPP)

- workflow_slug: run-wepp-reveg
  title: WEPP Reveg
  playback_type: run
  profile_slug: us-reveg
  playback_options: []
  schedule_pt: 04:10
  artifact_name: wepp-reveg-profile-run-log
  artifact_path: telemetry/wepp-reveg-profile-run.log
  description: Small US WEPP Reveg run with DAYMET climate

- workflow_slug: legacy-palouse
  title: Legacy Palouse
  playback_type: run
  profile_slug: legacy-palouse
  playback_options: []
  schedule_pt: 04:15
  artifact_name: legacy-palouse-profile-run-log
  artifact_path: telemetry/legacy-palouse-profile-run.log
  description: Small Legacy Palouse run with stochastic PRISM climate

- workflow_slug: rattlesnake-remove-rap-daymet-multi-interp-omni
  title: Daymet Multi-Interp Omni
  playback_type: run
  profile_slug: rattlesnake-remove-rap-daymet-multi-interp-omni
  playback_options: []
  schedule_pt: 03:17
  artifact_name: rattlesnake-remove-rap-daymet-multi-interp-omni-profile-run-log
  artifact_path: telemetry/rattlesnake-remove-rap-daymet-multi-interp-omni-profile-run.log
  description: Rattlesnake run with Daymet Multiple Interpolated Climates and Omni mulching scenarios

- workflow_slug: single-storm
  title: Single Storm
  playback_type: run
  profile_slug: single-storm
  playback_options: []
  schedule_pt: 05:40
  artifact_name: single-storm-profile-run-log
  artifact_path: telemetry/single-storm-profile-run.log
  description: 0 Single Storm Climate


- workflow_slug: rattlesnake-gridmet-interp-watar10mm-dss_export
  title: SBS GRIDMET Interp DSS Export
  playback_type: run
  profile_slug: rattlesnake-gridmet-interp-watar10mm-dss_export
  playback_options: []
  schedule_pt: 05:45
  artifact_name: rattlesnake-gridmet-interp-watar10mm-dss_export-profile-run-log
  artifact_path: telemetry/rattlesnake-gridmet-interp-watar10mm-dss_export-profile-run.log
  description: Rattlesnake SBS with GRIDMET Interpolated Climate, WATAR 10mm depth, DSS Export
