name: Pytest Coverage Nightly
true:
  schedule:
  - cron: 0 9 * * *
  workflow_dispatch: null
env:
  RUNNER_DOCKER_ENV: /workdir/wepppy/docker/.env
jobs:
  pytest-coverage:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - homelab
    timeout-minutes: 120
    steps:
    - name: Run pytest coverage suite
      run: 'set -euo pipefail

        scripts/run-pytest-coverage.sh

        '
    - name: Upload coverage artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-coverage
        path: coverage
        if-no-files-found: warn
