from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional, Sequence, Set

from wepppy.wepp.soils import HorizonMixin

__version__: str
ERIN_ADJUST_FCWP: bool
TRANSIENT_FIELDS: List[str]
colors: List[str]


class SsurgoRequestError(Exception): ...


class MajorComponent:
    def __init__(self, component: Dict[str, Any]) -> None: ...


class Horizon(HorizonMixin):
    def __init__(self, chkey: int, layer: Dict[str, Any], defaults: Optional[Dict[str, Any]] = ...) -> None: ...
    @property
    def clay(self) -> float: ...
    @property
    def sand(self) -> float: ...
    @property
    def cec(self) -> float: ...
    @property
    def vfs(self) -> float: ...
    @property
    def om(self) -> float: ...
    @property
    def depth(self) -> float: ...
    def valid(self) -> bool: ...


class SoilSummary:
    mukey: Optional[int]
    fname: str
    soils_dir: str
    build_date: str
    desc: str
    color: str

    def __init__(self, **kwargs: Any) -> None: ...
    def as_dict(self, abbreviated: bool = ...) -> Dict[str, Any]: ...
    @property
    def path(self) -> str: ...
    @property
    def meta_fn(self) -> Optional[str]: ...
    @property
    def meta(self) -> Any: ...
    def get_weppsoilutil(self) -> Any: ...
    @property
    def simple_texture(self) -> Optional[str]: ...
    @property
    def texture(self) -> Optional[str]: ...
    @property
    def smr(self) -> Any: ...
    @property
    def avke(self) -> Any: ...
    @property
    def clay(self) -> Any: ...
    @property
    def sand(self) -> Any: ...
    @property
    def soil_depth(self) -> Any: ...
    @property
    def rock(self) -> Any: ...
    @property
    def bd(self) -> Any: ...
    @property
    def ll(self) -> Any: ...


class WeppSoil:
    mukey: int

    def __init__(
        self,
        ssurgo_c: "SurgoSoilCollection",
        mukey: int,
        initial_sat: float = ...,
        horizon_defaults: Optional[Dict[str, Any]] = ...,
        res_lyr_ksat_threshold: float = ...,
        ksflag: bool = ...,
    ) -> None: ...
    @property
    def short_description(self) -> str: ...
    def build(self) -> None: ...
    def getFirstHorizon(self) -> Horizon: ...
    @property
    def has_majorComponent(self) -> bool: ...
    @property
    def has_horizons(self) -> bool: ...
    def build_file_contents(self, ag: bool = ...) -> str: ...
    def build_file_contents_v2006_2(self, ag: bool = ...) -> str: ...
    def valid(self) -> bool: ...
    @property
    def pickle_fn(self) -> Optional[str]: ...
    def pickle(self, wd: str = ..., overwrite: bool = ..., fname: Optional[str] = ...) -> None: ...
    def write(
        self,
        wd: str = ...,
        overwrite: bool = ...,
        fname: Optional[str] = ...,
        db_build: bool = ...,
        version: str = ...,
    ) -> SoilSummary: ...
    def write_log(
        self,
        wd: str = ...,
        overwrite: bool = ...,
        fname: Optional[str] = ...,
        db_build: bool = ...,
    ) -> None: ...


class SurgoCollectionWorkerViewFactory:
    def __init__(self, db_path: str) -> None: ...
    def build(self, mukeys: Set[int], source_data: str) -> Any: ...


class SurgoSoilCollection:
    weppSoils: Dict[int, WeppSoil]
    invalidSoils: Dict[int, Optional[WeppSoil]]

    def __init__(self, mukeys: Iterable[int], use_statsgo: bool = ...) -> None: ...
    def makeWeppSoils(
        self,
        initial_sat: float = ...,
        verbose: bool = ...,
        horizon_defaults: Optional[Dict[str, Any]] = ...,
        ksflag: bool = ...,
        logger: Optional[Any] = ...,
        max_workers: Optional[int] = ...,
    ) -> None: ...
    def writeWeppSoils(
        self,
        wd: str = ...,
        overwrite: bool = ...,
        write_logs: bool = ...,
        db_build: bool = ...,
        version: str = ...,
        pickle: bool = ...,
    ) -> Dict[int, SoilSummary]: ...
    def logInvalidSoils(self, wd: str = ..., overwrite: bool = ..., db_build: bool = ...) -> None: ...
    def getValidWeppSoils(self) -> List[int]: ...
    def getInValidWeppSoils(self) -> List[int]: ...
    def get_components(self, mukey: int) -> List[Dict[str, Any]]: ...
    def get_layers(self, cokey: int) -> List[Dict[str, Any]]: ...
    def get_fragvol_r(self, chkey: int) -> Optional[float]: ...
    def get_texture(self, chkey: int) -> str: ...
    def get_reskind(self, cokey: int) -> str: ...
    def dump(self, table: str, fname: str) -> None: ...


def query_mukeys_in_extent(extent: Sequence[float]) -> Optional[Set[int]]: ...
