#!/usr/bin/env python3
"""Generate a markdown summary of stub coverage under the wepppy package."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable


def iter_python_files(root: Path) -> Iterable[Path]:
    """Yield Python source files under ``root`` excluding stub files."""
    for path in root.rglob("*.py"):
        if path.suffix == ".py" and not path.name.endswith(".pyi"):
            yield path


def format_checkbox_line(path: Path, has_stub: bool) -> str:
    checkbox = "[x]" if has_stub else "[ ]"
    return f"- {checkbox} `{path.as_posix()}`"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        default="wepppy",
        type=Path,
        help="Root directory to scan for Python files (default: wepppy)",
    )
    parser.add_argument(
        "--output",
        default="TYPE_HINTS_SUMMARY.md",
        type=Path,
        help="Path to the markdown file to write (default: TYPE_HINTS_SUMMARY.md)",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    repo = Path.cwd()

    lines = ["# Stub Coverage Summary", "", "Generated by: `check_stub_coverage.py`", "", f"_Scanned root_: `{root.relative_to(repo)}`", ""]

    for py_file in sorted(iter_python_files(root)):
        rel_path = py_file.relative_to(repo)
        stub_path = py_file.with_suffix(".pyi")
        has_stub = stub_path.exists()
        lines.append(format_checkbox_line(rel_path, has_stub))

    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
