#!/usr/bin/env python3
"""Render RQ dependency graph docs from the static graph artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.extract_rq_dependency_graph import SOURCE_GLOBS, STATIC_GRAPH_PATH

CATALOG_PATH = Path("wepppy/rq/job-dependencies-catalog.md")
START_MARKER = "<!-- AUTO-GENERATED: RQ DEPENDENCY GRAPH START -->"
END_MARKER = "<!-- AUTO-GENERATED: RQ DEPENDENCY GRAPH END -->"


def _catalog_path(repo_root: Path | None = None) -> Path:
    root = (repo_root or REPO_ROOT).resolve()
    return root / CATALOG_PATH


def _static_graph_path(repo_root: Path | None = None) -> Path:
    root = (repo_root or REPO_ROOT).resolve()
    return root / STATIC_GRAPH_PATH


def load_static_edges(*, repo_root: Path | None = None) -> list[dict[str, Any]]:
    graph_path = _static_graph_path(repo_root)
    return json.loads(graph_path.read_text(encoding="utf-8"))


def _render_depends_on(depends_on: list[str]) -> str:
    if not depends_on:
        return "*(none)*"
    return ", ".join(f"`{dep}`" for dep in depends_on)


def _render_source_globs() -> str:
    return ", ".join(f"`{pattern}`" for pattern in SOURCE_GLOBS)


def render_managed_section(edges: list[dict[str, Any]]) -> str:
    unique_targets = sorted({str(edge.get("enqueue_target")) for edge in edges})
    group_keys = sorted(
        {
            (
                str(edge.get("source_module")),
                str(edge.get("source_function")),
            )
            for edge in edges
        }
    )
    grouped: dict[tuple[str, str], list[dict[str, Any]]] = {key: [] for key in group_keys}
    for edge in edges:
        grouped[(str(edge.get("source_module")), str(edge.get("source_function")))].append(edge)

    lines = [
        "## Automated Dependency Graph",
        "",
        "This section is generated by `tools/render_rq_dependency_graph_docs.py` from",
        "`wepppy/rq/job-dependency-graph.static.json`. Do not edit this block manually.",
        "",
        f"- Extracted enqueue edges: `{len(edges)}`",
        f"- Unique enqueue targets: `{len(unique_targets)}`",
        f"- Source globs: {_render_source_globs()}",
    ]

    for group_key in group_keys:
        module_path, function_name = group_key
        lines.extend(
            [
                "",
                f"### `{module_path}::{function_name}`",
            ]
        )
        group_edges = sorted(
            grouped[group_key],
            key=lambda item: (
                int(item.get("source_lineno", 0)),
                str(item.get("enqueue_target", "")),
                str(item.get("queue_name", "")),
                str(item.get("job_meta_stage", "")),
            ),
        )
        for edge in group_edges:
            stage = str(edge.get("job_meta_stage") or "untracked")
            queue_name = str(edge.get("queue_name") or "unknown")
            target = str(edge.get("enqueue_target") or "<unknown>")
            depends = _render_depends_on(list(edge.get("depends_on") or []))
            lineno = int(edge.get("source_lineno") or 0)
            lines.append(
                f"- line `{lineno}` queue `{queue_name}` stage `{stage}` enqueue `{target}` depends_on {depends}"
            )

    return "\n".join(lines).rstrip() + "\n"


def replace_managed_section(*, document_text: str, managed_content: str) -> str:
    start_index = document_text.find(START_MARKER)
    end_index = document_text.find(END_MARKER)
    if start_index < 0 or end_index < 0 or end_index < start_index:
        raise RuntimeError(
            "Catalog markers are missing. Expected both start/end AUTO-GENERATED RQ dependency markers."
        )

    before = document_text[: start_index + len(START_MARKER)]
    after = document_text[end_index:]
    managed = managed_content.strip("\n")
    return f"{before}\n{managed}\n{after}"


def render_catalog_text(*, repo_root: Path | None = None, edges: list[dict[str, Any]] | None = None) -> str:
    root = (repo_root or REPO_ROOT).resolve()
    catalog_path = _catalog_path(root)
    current_text = catalog_path.read_text(encoding="utf-8")
    managed = render_managed_section(edges if edges is not None else load_static_edges(repo_root=root))
    return replace_managed_section(document_text=current_text, managed_content=managed)


def _write_catalog(*, repo_root: Path | None = None) -> int:
    root = (repo_root or REPO_ROOT).resolve()
    catalog_path = _catalog_path(root)
    edges = load_static_edges(repo_root=root)
    rendered_text = render_catalog_text(repo_root=root, edges=edges)
    catalog_path.write_text(rendered_text, encoding="utf-8")
    rel = catalog_path.relative_to(root).as_posix()
    print(f"updated managed catalog section in {rel} using {len(edges)} edges")
    return 0


def _check_catalog(*, repo_root: Path | None = None) -> int:
    root = (repo_root or REPO_ROOT).resolve()
    catalog_path = _catalog_path(root)
    current = catalog_path.read_text(encoding="utf-8")
    rendered = render_catalog_text(repo_root=root)
    if current != rendered:
        rel = catalog_path.relative_to(root).as_posix()
        print("RQ dependency graph drift detected:")
        print(f"- {rel}")
        return 1
    rel = catalog_path.relative_to(root).as_posix()
    print(f"RQ dependency graph catalog is up to date ({rel})")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write the managed doc section.")
    parser.add_argument("--check", action="store_true", help="Fail if the managed section is stale.")
    args = parser.parse_args(argv)

    if not args.write and not args.check:
        print(render_catalog_text(repo_root=REPO_ROOT), end="")
        return 0

    if args.write:
        _write_catalog(repo_root=REPO_ROOT)
    if args.check:
        return _check_catalog(repo_root=REPO_ROOT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
