"""SWAT+ print.prt configuration helpers."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, List, Optional, Sequence, Tuple

PRINT_PRT_DAILY = 1
PRINT_PRT_MONTHLY = 2
PRINT_PRT_YEARLY = 4
PRINT_PRT_AVANN = 8

DEFAULT_PRINT_PRT_TITLE = "print.prt: generated by WEPPpy"

DEFAULT_PRINT_PRT_FLAGS_PRIMARY: List[Tuple[str, str]] = [
    ("csvout", "n"),
    ("dbout", "n"),
    ("cdfout", "n"),
]

DEFAULT_PRINT_PRT_FLAGS_SECONDARY: List[Tuple[str, str]] = [
    ("soilout", "n"),
    ("mgtout", "n"),
    ("hydcon", "n"),
    ("fdcout", "n"),
]

PRINT_PRT_OBJECT_ORDER: List[str] = [
    "basin_wb",
    "basin_nb",
    "basin_ls",
    "basin_pw",
    "basin_aqu",
    "basin_res",
    "basin_cha",
    "basin_sd_cha",
    "basin_psc",
    "region_wb",
    "region_nb",
    "region_ls",
    "region_pw",
    "region_aqu",
    "region_res",
    "region_sd_cha",
    "region_psc",
    "water_allo",
    "lsunit_wb",
    "lsunit_nb",
    "lsunit_ls",
    "lsunit_pw",
    "hru_wb",
    "hru_nb",
    "hru_ls",
    "hru_pw",
    "hru_cb",
    "hru-lte_wb",
    "hru-lte_nb",
    "hru-lte_ls",
    "hru-lte_pw",
    "channel",
    "channel_sd",
    "aquifer",
    "reservoir",
    "recall",
    "hyd",
    "ru",
    "pest",
]

PRINT_PRT_OBJECT_ORDER_NO_HRU_CB: List[str] = [
    name for name in PRINT_PRT_OBJECT_ORDER if name != "hru_cb"
]

__all__ = [
    "DEFAULT_PRINT_PRT_FLAGS_PRIMARY",
    "DEFAULT_PRINT_PRT_FLAGS_SECONDARY",
    "DEFAULT_PRINT_PRT_TITLE",
    "PRINT_PRT_AVANN",
    "PRINT_PRT_DAILY",
    "PRINT_PRT_MONTHLY",
    "PRINT_PRT_OBJECT_ORDER",
    "PRINT_PRT_OBJECT_ORDER_NO_HRU_CB",
    "PRINT_PRT_YEARLY",
    "PrintPrtConfig",
    "PrintPrtObjects",
    "load_print_prt",
    "mask_from_flags",
    "mask_from_tokens",
    "mask_to_tokens",
    "parse_print_prt",
]


def mask_from_flags(
    *,
    daily: bool = False,
    monthly: bool = False,
    yearly: bool = False,
    avann: bool = False,
) -> int:
    mask = 0
    if daily:
        mask |= PRINT_PRT_DAILY
    if monthly:
        mask |= PRINT_PRT_MONTHLY
    if yearly:
        mask |= PRINT_PRT_YEARLY
    if avann:
        mask |= PRINT_PRT_AVANN
    return mask


def mask_from_tokens(daily: str, monthly: str, yearly: str, avann: str) -> int:
    return mask_from_flags(
        daily=daily.strip().lower() == "y",
        monthly=monthly.strip().lower() == "y",
        yearly=yearly.strip().lower() == "y",
        avann=avann.strip().lower() == "y",
    )


def mask_to_tokens(mask: int) -> Tuple[str, str, str, str]:
    return (
        "y" if mask & PRINT_PRT_DAILY else "n",
        "y" if mask & PRINT_PRT_MONTHLY else "n",
        "y" if mask & PRINT_PRT_YEARLY else "n",
        "y" if mask & PRINT_PRT_AVANN else "n",
    )


def _object_attr_name(object_name: str) -> str:
    return object_name.replace("-", "_")


@dataclass
class PrintPrtObjects:
    """Bitmask settings for each print.prt object output."""

    basin_wb: int = PRINT_PRT_YEARLY | PRINT_PRT_AVANN
    basin_nb: int = PRINT_PRT_AVANN
    basin_ls: int = PRINT_PRT_AVANN
    basin_pw: int = PRINT_PRT_AVANN
    basin_aqu: int = PRINT_PRT_AVANN
    basin_res: int = PRINT_PRT_AVANN
    basin_cha: int = PRINT_PRT_AVANN
    basin_sd_cha: int = PRINT_PRT_AVANN
    basin_psc: int = PRINT_PRT_AVANN
    region_wb: int = PRINT_PRT_AVANN
    region_nb: int = PRINT_PRT_AVANN
    region_ls: int = PRINT_PRT_AVANN
    region_pw: int = PRINT_PRT_AVANN
    region_aqu: int = PRINT_PRT_AVANN
    region_res: int = PRINT_PRT_AVANN
    region_sd_cha: int = PRINT_PRT_AVANN
    region_psc: int = PRINT_PRT_AVANN
    water_allo: int = PRINT_PRT_AVANN
    lsunit_wb: int = PRINT_PRT_AVANN
    lsunit_nb: int = PRINT_PRT_AVANN
    lsunit_ls: int = PRINT_PRT_AVANN
    lsunit_pw: int = PRINT_PRT_AVANN
    hru_wb: int = PRINT_PRT_AVANN
    hru_nb: int = PRINT_PRT_AVANN
    hru_ls: int = PRINT_PRT_AVANN
    hru_pw: int = PRINT_PRT_AVANN
    hru_cb: int = PRINT_PRT_AVANN
    hru_lte_wb: int = PRINT_PRT_AVANN
    hru_lte_nb: int = PRINT_PRT_AVANN
    hru_lte_ls: int = PRINT_PRT_AVANN
    hru_lte_pw: int = PRINT_PRT_AVANN
    channel: int = PRINT_PRT_AVANN
    channel_sd: int = PRINT_PRT_AVANN
    aquifer: int = PRINT_PRT_AVANN
    reservoir: int = PRINT_PRT_AVANN
    recall: int = 0
    hyd: int = PRINT_PRT_AVANN
    ru: int = PRINT_PRT_AVANN
    pest: int = PRINT_PRT_AVANN

    def iter_rows(self, order: Optional[Sequence[str]] = None) -> List[Tuple[str, int]]:
        rows: List[Tuple[str, int]] = []
        for object_name in order or PRINT_PRT_OBJECT_ORDER:
            attr_name = _object_attr_name(object_name)
            if not hasattr(self, attr_name):
                raise ValueError(f"Unsupported print.prt object: {object_name}")
            rows.append((object_name, int(getattr(self, attr_name))))
        return rows

    def set_mask(self, object_name: str, mask: int) -> None:
        attr_name = _object_attr_name(object_name)
        if not hasattr(self, attr_name):
            raise ValueError(f"Unsupported print.prt object: {object_name}")
        setattr(self, attr_name, int(mask))


@dataclass
class PrintPrtConfig:
    """Structured print.prt configuration."""

    title: str = DEFAULT_PRINT_PRT_TITLE
    nyskip: int = 3
    day_start: int = 0
    yrc_start: int = 0
    day_end: int = 0
    yrc_end: int = 0
    interval: int = 1
    aa_int_cnt: int = 0
    flags_primary: List[Tuple[str, str]] = field(
        default_factory=lambda: list(DEFAULT_PRINT_PRT_FLAGS_PRIMARY)
    )
    flags_secondary: List[Tuple[str, str]] = field(
        default_factory=lambda: list(DEFAULT_PRINT_PRT_FLAGS_SECONDARY)
    )
    flags_extra: List[List[Tuple[str, str]]] = field(default_factory=list)
    object_order: List[str] = field(default_factory=lambda: list(PRINT_PRT_OBJECT_ORDER))
    objects: PrintPrtObjects = field(default_factory=PrintPrtObjects)

    def render(self) -> str:
        lines: List[str] = [
            self.title,
            "nyskip      day_start  yrc_start  day_end   yrc_end   interval",
            (
                f"{self.nyskip:<11}"
                f"{self.day_start:<10}"
                f"{self.yrc_start:<10}"
                f"{self.day_end:<10}"
                f"{self.yrc_end:<10}"
                f"{self.interval:<10}"
            ).rstrip(),
            "aa_int_cnt",
            str(self.aa_int_cnt),
        ]

        lines.extend(_format_flag_block(self.flags_primary))
        lines.extend(_format_flag_block(self.flags_secondary))
        for block in self.flags_extra:
            lines.extend(_format_flag_block(block))

        lines.append("objects                  daily       monthly        yearly         avann")
        for object_name, mask in self.objects.iter_rows(self.object_order):
            daily, monthly, yearly, avann = mask_to_tokens(mask)
            lines.append(
                f"{object_name:<24}"
                f"{daily:<13}"
                f"{monthly:<13}"
                f"{yearly:<13}"
                f"{avann:<13}".rstrip()
            )
        return "\n".join(lines) + "\n"


def _format_flag_block(flags: Iterable[Tuple[str, str]]) -> List[str]:
    names: List[str] = []
    values: List[str] = []
    for name, value in flags:
        names.append(f"{name:<12}")
        values.append(f"{value:<12}")
    return ["".join(names).rstrip(), "".join(values).rstrip()]


def load_print_prt(path: str) -> PrintPrtConfig:
    with open(path, "r") as handle:
        return parse_print_prt(handle.read())


def parse_print_prt(text: str) -> PrintPrtConfig:
    lines = [line.rstrip() for line in text.splitlines()]
    if not lines:
        return PrintPrtConfig()

    idx = 0
    while idx < len(lines) and not lines[idx].strip():
        idx += 1
    title = lines[idx].strip() if idx < len(lines) else DEFAULT_PRINT_PRT_TITLE
    idx += 1

    idx = _seek_line(lines, idx, "nyskip")
    nyskip, day_start, yrc_start, day_end, yrc_end, interval = (
        3,
        0,
        0,
        0,
        0,
        1,
    )
    if idx is not None and idx + 1 < len(lines):
        values = lines[idx + 1].split()
        nyskip = _parse_int(values, 0, nyskip)
        day_start = _parse_int(values, 1, day_start)
        yrc_start = _parse_int(values, 2, yrc_start)
        day_end = _parse_int(values, 3, day_end)
        yrc_end = _parse_int(values, 4, yrc_end)
        interval = _parse_int(values, 5, interval)
        idx += 2
    else:
        idx = 0

    idx = _seek_line(lines, idx, "aa_int_cnt")
    aa_int_cnt = 0
    if idx is not None and idx + 1 < len(lines):
        aa_int_cnt = _parse_int(lines[idx + 1].split(), 0, aa_int_cnt)
        idx += 2
    else:
        idx = 0

    flag_blocks: List[List[Tuple[str, str]]] = []
    objects_idx = _seek_line(lines, idx, "objects")
    parse_idx = idx
    if objects_idx is None:
        objects_idx = len(lines)
    while parse_idx < objects_idx:
        if not lines[parse_idx].strip():
            parse_idx += 1
            continue
        names = lines[parse_idx].split()
        if not names or parse_idx + 1 >= objects_idx:
            break
        values = lines[parse_idx + 1].split()
        pairs = [
            (name, values[offset] if offset < len(values) else "n")
            for offset, name in enumerate(names)
        ]
        flag_blocks.append(pairs)
        parse_idx += 2

    if objects_idx < len(lines) and lines[objects_idx].strip().startswith("objects"):
        objects_idx += 1

    objects = PrintPrtObjects()
    object_order: List[str] = []
    for line in lines[objects_idx:]:
        if not line.strip():
            continue
        parts = line.split()
        if len(parts) < 5:
            continue
        name = parts[0]
        mask = mask_from_tokens(parts[1], parts[2], parts[3], parts[4])
        objects.set_mask(name, mask)
        object_order.append(name)

    flags_primary = (
        list(flag_blocks[0]) if len(flag_blocks) > 0 else list(DEFAULT_PRINT_PRT_FLAGS_PRIMARY)
    )
    flags_secondary = (
        list(flag_blocks[1]) if len(flag_blocks) > 1 else list(DEFAULT_PRINT_PRT_FLAGS_SECONDARY)
    )
    flags_extra = [list(block) for block in flag_blocks[2:]] if len(flag_blocks) > 2 else []

    return PrintPrtConfig(
        title=title or DEFAULT_PRINT_PRT_TITLE,
        nyskip=nyskip,
        day_start=day_start,
        yrc_start=yrc_start,
        day_end=day_end,
        yrc_end=yrc_end,
        interval=interval,
        aa_int_cnt=aa_int_cnt,
        flags_primary=flags_primary,
        flags_secondary=flags_secondary,
        flags_extra=flags_extra,
        object_order=object_order or list(PRINT_PRT_OBJECT_ORDER),
        objects=objects,
    )


def _parse_int(values: List[str], index: int, default: int) -> int:
    if index >= len(values):
        return default
    try:
        return int(values[index])
    except (TypeError, ValueError):
        return default


def _seek_line(lines: List[str], start: int, token: str) -> Optional[int]:
    for idx in range(start, len(lines)):
        if token in lines[idx]:
            return idx
    return None
