"""TxtInOut preparation and climate/recall patch helpers for SWAT NoDb."""

from __future__ import annotations

import os
import shutil
from os.path import exists as _exists
from os.path import join as _join
from typing import Dict, List, Optional

import duckdb

from wepppy.nodir.parquet_sidecars import pick_existing_parquet_path

from ._helpers import (
    _escape_sql_path,
    _quote_ident,
    _read_parquet_columns,
    _resolve_column,
    _resolve_column_optional,
)
from .errors import SwatNoDbLockedException


class SwatTxtInOutMixin:
    def _prepare_txtinout(self) -> None:
        if not _exists(self.template_dir):
            raise FileNotFoundError(f"Missing SWAT template directory: {self.template_dir}")
        if _exists(self.swat_txtinout_dir):
            shutil.rmtree(self.swat_txtinout_dir)
        shutil.copytree(self.template_dir, self.swat_txtinout_dir)
        recall_dirs = set()
        if self.recall_subdir:
            recall_dirs.add(self.recall_subdir)
        recall_dirs.add("recall")
        for dir_name in recall_dirs:
            if not dir_name:
                continue
            candidate = _join(self.swat_txtinout_dir, dir_name)
            if _exists(candidate):
                shutil.rmtree(candidate)
        self._ensure_om_water_init()
        self._ensure_plant_ini()
        self._patch_hru_surf_storage()

    def _ensure_om_water_init(self) -> None:
        om_path = _join(self.swat_txtinout_dir, "om_water.ini")
        if _exists(om_path):
            return
        header = (
            "name flo sed orgn sedp no3 solp chla nh3 no2 cbod dox "
            "san sil cla sag lag grv temp"
        )
        zeros = "0 " * 17 + "0"
        content = "\n".join(
            [
                "om_water.ini: generated by WEPPpy",
                header,
                f"no_init {zeros}",
                "",
            ]
        )
        with open(om_path, "w") as handle:
            handle.write(content)

    def _ensure_plant_ini(self) -> None:
        plant_path = _join(self.swat_txtinout_dir, "plant.ini")
        communities = self._read_landuse_communities()
        if not communities:
            return

        plant_names = self._read_plant_names()
        if not plant_names:
            return

        if not _exists(plant_path):
            self._write_plant_ini(plant_path, communities, plant_names)
            return

        existing = self._read_plant_ini_communities(plant_path)
        missing = [comm for comm in communities if comm not in existing]
        if missing:
            self._append_plant_ini(plant_path, missing, plant_names)

    def _read_landuse_communities(self) -> List[str]:
        landuse_path = _join(self.swat_txtinout_dir, "landuse.lum")
        if not _exists(landuse_path):
            return []
        with open(landuse_path) as handle:
            lines = handle.read().splitlines()
        if len(lines) < 3:
            return []
        header = lines[1].split()
        col_idx = None
        for idx, name in enumerate(header):
            if name.lower() in ("plnt_com", "plant_com", "plant_comm", "plant_community"):
                col_idx = idx
                break
        if col_idx is None:
            return []
        communities: List[str] = []
        for line in lines[2:]:
            parts = line.split()
            if len(parts) <= col_idx:
                continue
            name = parts[col_idx]
            if not name or name.lower() == "null":
                continue
            if name not in communities:
                communities.append(name)
        return communities

    def _read_plant_names(self) -> List[str]:
        plants_path = _join(self.swat_txtinout_dir, "plants.plt")
        if not _exists(plants_path):
            return []
        with open(plants_path) as handle:
            lines = handle.read().splitlines()
        if len(lines) < 3:
            return []
        names: List[str] = []
        for line in lines[2:]:
            parts = line.split()
            if not parts:
                continue
            name = parts[0]
            if name not in names:
                names.append(name)
        return names

    def _read_plant_ini_communities(self, plant_path: str) -> List[str]:
        with open(plant_path) as handle:
            lines = handle.read().splitlines()
        if len(lines) < 3:
            return []
        communities: List[str] = []
        idx = 2
        while idx < len(lines):
            parts = lines[idx].split()
            if len(parts) < 2:
                idx += 1
                continue
            name = parts[0]
            try:
                count = int(float(parts[1]))
            except ValueError:
                count = 0
            communities.append(name)
            idx += 1 + max(count, 0)
        return communities

    def _choose_plant_for_community(self, community: str, plant_names: List[str]) -> str:
        plant_set = {name.lower(): name for name in plant_names}
        comm = community.lower()
        base = comm
        if comm.endswith("_comm"):
            base = comm[:-5]
        if base in plant_set:
            return plant_set[base]
        if "rye" in comm and "rye" in plant_set:
            return plant_set["rye"]
        if "rice" in comm:
            if "rice140" in plant_set and "140" in comm:
                return plant_set["rice140"]
            if "rice" in plant_set:
                return plant_set["rice"]
        for prefix in ("frst", "frse", "gras", "wetn", "wetw", "orcd", "agrl"):
            if prefix in comm and prefix in plant_set:
                return plant_set[prefix]
        if "agrl" in plant_set:
            return plant_set["agrl"]
        return plant_names[0]

    def _write_plant_ini(
        self,
        plant_path: str,
        communities: List[str],
        plant_names: List[str],
    ) -> None:
        header = (
            "pcom_name plt_cnt rot_yr_ini plt_name lc_status "
            "lai_init bm_init phu_init plnt_pop yrs_init rsd_init"
        )
        lines = ["plant.ini: generated by WEPPpy", header]
        for comm in communities:
            plant = self._choose_plant_for_community(comm, plant_names)
            lines.append(f"{comm} 1 1")
            lines.append(
                f"{plant} n 0.00000 0.00000 0.00000 10000.00000 0.00000 0.00000"
            )
        with open(plant_path, "w") as handle:
            handle.write("\n".join(lines) + "\n")

    def _append_plant_ini(
        self,
        plant_path: str,
        communities: List[str],
        plant_names: List[str],
    ) -> None:
        lines = []
        for comm in communities:
            plant = self._choose_plant_for_community(comm, plant_names)
            lines.append(f"{comm} 1 1")
            lines.append(
                f"{plant} n 0.00000 0.00000 0.00000 10000.00000 0.00000 0.00000"
            )
        with open(plant_path, "a") as handle:
            handle.write("\n".join(lines) + "\n")

    def _patch_hru_surf_storage(self) -> None:
        hru_path = _join(self.swat_txtinout_dir, "hru-data.hru")
        if not _exists(hru_path):
            return
        with open(hru_path) as handle:
            lines = handle.read().splitlines()
        if len(lines) < 3:
            return
        header = lines[1].split()
        surf_idx = None
        for idx, name in enumerate(header):
            if name.lower() in ("surf_stor", "surfstor", "surf_store"):
                surf_idx = idx
                break
        if surf_idx is None:
            return
        updated = False
        for idx in range(2, len(lines)):
            parts = lines[idx].split()
            if len(parts) <= surf_idx:
                continue
            if parts[surf_idx].lower() != "null":
                parts[surf_idx] = "null"
                lines[idx] = " ".join(parts)
                updated = True
        if updated:
            with open(hru_path, "w") as handle:
                handle.write("\n".join(lines) + "\n")

    def _normalize_climate_nbyr(self) -> None:
        cli_files = ("pcp.cli", "tmp.cli", "slr.cli", "wnd.cli", "hmd.cli", "pet.cli")
        for cli_name in cli_files:
            cli_path = _join(self.swat_txtinout_dir, cli_name)
            if not _exists(cli_path):
                continue
            for filename in self._read_cli_filenames(cli_path):
                data_path = _join(self.swat_txtinout_dir, filename)
                if not _exists(data_path):
                    continue
                if self._patch_cli_nbyr(data_path):
                    self.logger.info("SWAT build: updated nbyr in %s", data_path)

    def _validate_recall_wst(self) -> None:
        stations = self._load_weather_station_names()
        if not stations:
            raise FileNotFoundError(
                f"Missing or empty weather-sta.cli in {self.swat_txtinout_dir}"
            )
        recall_wst = (self.recall_wst or "").strip()
        if recall_wst.lower() == "auto" or not recall_wst:
            self.recall_wst = stations[0]
            self.logger.info(
                "SWAT build: recall_wst auto-selected '%s' from weather-sta.cli",
                self.recall_wst,
            )
            return
        if recall_wst not in stations:
            if recall_wst.lower() == "wea1":
                self.recall_wst = stations[0]
                self.logger.warning(
                    "SWAT build: recall_wst 'wea1' not found; defaulting to '%s'. "
                    "Set recall_wst=auto or an explicit station to avoid this warning.",
                    self.recall_wst,
                )
                return
            raise SwatNoDbLockedException(
                f"recall_wst '{self.recall_wst}' not found in weather-sta.cli; available: {', '.join(stations)}"
            )

    def _load_weather_station_names(self) -> List[str]:
        cli_path = _join(self.swat_txtinout_dir, "weather-sta.cli")
        if not _exists(cli_path):
            return []
        with open(cli_path) as handle:
            lines = handle.read().splitlines()
        if len(lines) < 3:
            return []
        stations: List[str] = []
        for line in lines[2:]:
            parts = line.split()
            if not parts:
                continue
            stations.append(parts[0])
        return stations

    def _read_cli_filenames(self, cli_path: str) -> List[str]:
        with open(cli_path) as handle:
            lines = handle.read().splitlines()
        if len(lines) < 3:
            return []
        filenames: List[str] = []
        for line in lines[2:]:
            parts = line.split()
            if not parts:
                continue
            filenames.append(parts[0])
        return filenames

    def _patch_cli_nbyr(self, data_path: str) -> bool:
        with open(data_path) as handle:
            lines = handle.read().splitlines()
        if len(lines) < 4:
            return False
        values = lines[2].split()
        if not values:
            return False
        try:
            nbyr = int(float(values[0]))
        except ValueError:
            return False

        count = 0
        last_year: Optional[str] = None
        for line in lines[3:]:
            parts = line.split()
            if not parts:
                continue
            year = parts[0]
            if year != last_year:
                count += 1
                last_year = year
        if count == 0 or count == nbyr:
            return False
        values[0] = str(count)
        lines[2] = " ".join(values)
        with open(data_path, "w") as handle:
            handle.write("\n".join(lines) + "\n")
        return True

    def _normalize_recall_paths(self) -> None:
        recall_path = _join(self.swat_txtinout_dir, "recall.rec")
        if not _exists(recall_path):
            return
        with open(recall_path) as handle:
            lines = handle.read().splitlines()
        if len(lines) < 3:
            return
        header = lines[1].split()
        fname_idx = None
        for idx, name in enumerate(header):
            if name.lower() in ("filename", "fname"):
                fname_idx = idx
                break
        if fname_idx is None:
            fname_idx = 3

        updated = False
        for idx in range(2, len(lines)):
            parts = lines[idx].split()
            if len(parts) <= fname_idx:
                continue
            raw = parts[fname_idx]
            if not raw:
                continue
            normalized = raw.replace("\\", "/").lstrip("./")
            basename = os.path.basename(normalized)
            dest = _join(self.swat_txtinout_dir, basename)
            if not _exists(dest):
                src = None
                if normalized:
                    candidate = normalized
                    if os.path.isabs(candidate):
                        src = candidate if _exists(candidate) else None
                    else:
                        candidate = _join(self.swat_txtinout_dir, candidate)
                        if _exists(candidate):
                            src = candidate
                if src is None and self.recall_subdir:
                    candidate = _join(self.swat_txtinout_dir, self.recall_subdir, basename)
                    if _exists(candidate):
                        src = candidate
                if src is not None:
                    shutil.copy2(src, dest)

            if basename != raw:
                parts[fname_idx] = basename
                lines[idx] = " ".join(parts)
                updated = True

        if updated:
            with open(recall_path, "w") as handle:
                handle.write("\n".join(lines) + "\n")

    def _patch_recall_con_areas(self) -> None:
        recall_con = _join(self.swat_txtinout_dir, "recall.con")
        if not _exists(recall_con):
            return

        areas = self._load_hillslope_areas()
        if not areas:
            return

        with open(recall_con) as handle:
            lines = handle.read().splitlines()
        if len(lines) < 3:
            return

        header = lines[1].split()
        area_idx = None
        gis_idx = None
        for idx, name in enumerate(header):
            lower = name.lower()
            if lower in ("area_ha", "area"):
                area_idx = idx
            if lower in ("gis_id", "gisid"):
                gis_idx = idx
        if area_idx is None or gis_idx is None:
            return

        updated = False
        for idx in range(2, len(lines)):
            parts = lines[idx].split()
            if len(parts) <= max(area_idx, gis_idx):
                continue
            try:
                wepp_id = int(float(parts[gis_idx]))
            except ValueError:
                continue
            area_ha = areas.get(wepp_id)
            if area_ha is None:
                continue
            parts[area_idx] = f"{area_ha:.3f}"
            lines[idx] = " ".join(parts)
            updated = True

        if updated:
            with open(recall_con, "w") as handle:
                handle.write("\n".join(lines) + "\n")

    def _load_hillslope_areas(self) -> Dict[int, float]:
        hillslopes_path = pick_existing_parquet_path(self.wd, "watershed/hillslopes.parquet")
        if hillslopes_path is None:
            return {}
        hillslopes_parquet = str(hillslopes_path)
        with duckdb.connect() as con:
            cols = _read_parquet_columns(con, hillslopes_parquet)
            wepp_col = _resolve_column(cols, ("wepp_id", "WeppID"), hillslopes_parquet)
            area_col = _resolve_column_optional(cols, ("area", "area_m2", "area_m", "area_sq_m"))
            if area_col is None:
                return {}
            rows = con.execute(
                "SELECT {wepp}, {area} FROM read_parquet('{path}')".format(
                    wepp=_quote_ident(wepp_col),
                    area=_quote_ident(area_col),
                    path=_escape_sql_path(hillslopes_parquet),
                )
            ).fetchall()
        areas: Dict[int, float] = {}
        for wepp_id, area_m2 in rows:
            if wepp_id is None or area_m2 is None:
                continue
            try:
                area_val = float(area_m2)
            except (TypeError, ValueError):
                continue
            if area_val <= 0.0:
                continue
            areas[int(wepp_id)] = area_val / 10_000.0
        return areas

