from __future__ import annotations

from typing import Any, MutableMapping

from flask import Blueprint, Response

from wepppy.climates.cligen import StationMeta
from wepppy.nodb.core.climate import Climate, ClimateStationMode
from wepppy.nodb.core import Ron

StationOption = MutableMapping[str, Any]

climate_bp: Blueprint

def set_climatestation_mode(runid: str, config: str) -> Response: ...

def set_climatestation(runid: str, config: str) -> Response: ...

def task_upload_cli(runid: str, config: str) -> Response: ...

def query_climatestation(runid: str, config: str) -> Response: ...

def query_climate_has_observed(runid: str, config: str) -> Response: ...

def report_climate(runid: str, config: str) -> Response: ...

def set_climate_mode(runid: str, config: str) -> Response: ...

def set_climate_spatialmode(runid: str, config: str) -> Response: ...

def view_closest_stations(runid: str, config: str) -> Response: ...

def view_heuristic_stations(runid: str, config: str) -> Response: ...

def view_station_par(runid: str, config: str) -> Response: ...

def view_eu_heuristic_stations(runid: str, config: str) -> Response: ...

def view_au_heuristic_stations(runid: str, config: str) -> Response: ...

def view_climate_monthlies(runid: str, config: str) -> Response: ...

def task_set_use_gridmet_wind_when_applicable(runid: str, config: str) -> Response: ...
