from __future__ import annotations

from flask import Blueprint, Response

landuse_bp: Blueprint

def set_landuse_mode(runid: str, config: str) -> Response: ...

def set_landuse_db(runid: str, config: str) -> Response: ...

def modify_landuse_coverage(runid: str, config: str) -> Response: ...

def task_modify_landuse_mapping(runid: str, config: str) -> Response: ...

def query_landuse(runid: str, config: str) -> Response: ...

def query_landuse_subcatchments(runid: str, config: str) -> Response: ...

def query_landuse_channels(runid: str, config: str) -> Response: ...

def report_landuse(runid: str, config: str) -> Response: ...

def task_modify_landuse(runid: str, config: str) -> Response: ...

def query_landuse_cover_subcatchments(runid: str, config: str) -> Response: ...
