from __future__ import annotations

from flask import Blueprint, Response

landuse_bp: Blueprint

def query_landuse(runid: str, config: str) -> Response: ...

def query_landuse_subcatchments(runid: str, config: str) -> Response: ...

def query_landuse_channels(runid: str, config: str) -> Response: ...

def report_landuse(runid: str, config: str) -> Response: ...

def view_landuse_user_defined(runid: str, config: str) -> Response: ...

def view_landuse_map(runid: str, config: str) -> Response: ...

def query_landuse_cover_subcatchments(runid: str, config: str) -> Response: ...
